### ISSUE TITLE
Add a variable to cmake to determine static or shared linked boost

### ISSUE THREAD

**Issue by NobbZ** [exercism/cpp#126]
On my system I do have a shared boost and linking it statically fails for some unknown reason. Currently I change those lines in CMakeLists.txt and the *_test.cpp by hand.

But shouldn't it be possible to provide a variable that can be set by the student and then create appropriate *_test.cpp?

As far as I can remember, cmake is able to pre-process any kind of file.

**Comment by patricksjackson** [comment]
Ah, it is possible, but modifying the source in CMake would be a bit odd. Regardless, this issue is outdated as Boost is now removed from the majority of the track, see #233. Closing.
