### ISSUE TITLE
Create exercises specific to generic programming in C++

### ISSUE THREAD

**Issue by LegalizeAdulthood** [exercism/cpp#14]
Generic programming in C++ presents some interesting design choices.  For instance we could create an exercise that did not fix the specific data type for computing prime factors of a number.  We would only require that the data type used model the concept of an integer.  It could be signed, unsigned, arbitrary precision, bignum, fixed-point, etc.

Prime factors may or may not be a good example to demonstrate generic programming techniques, but it might be a good stepping stone to start down a series of exercises that involve more and more generic programming techniques.

I think these generic programming exercises should come later in the sequence because it's a fairly advanced topic that many day-to-day C++ programmers don't get into.  They consume generic code all the time, but don't often write generic code.

Here are some topics I think we should consider for generic programming exercises:
- Type functions along the lines of [`std::is_integral<T>`](http://en.cppreference.com/w/cpp/types/is_integral)
- Using type traits classes, such as associating enum values with a specific type derived from a common interface type
- Generic containers, perhaps a [quadtree](https://en.wikipedia.org/wiki/Quadtree)
- Generic algorithms

I think some of the designs presented in [Modern C++ Design](https://en.wikipedia.org/wiki/Modern_C%2B%2B_Design) could serve as starting points for exercises as well.

**Comment by patricksjackson** [comment]
We've added one generic programming exercise, binary-search-tree, and I have been tending to consider pushing for that in new problems where it makes sense.

I'll leave this open for now, as it would be a good idea to improve the track by trying to teach this. It may be a good thing to keep in mind for #237.

**Comment by patricksjackson** [comment]
Exercism v3 plans supercede this.
