### ISSUE TITLE
Missing UUIDs

### ISSUE THREAD

**Issue by kytrinyx** [exercism/cpp#144]
Configlet will warn about this soon (if it isn't already), but we're missing some of the nextercism config data for two exercises:

https://github.com/exercism/cpp/blob/master/config.json#L406-L420

**Comment by NobbZ** [comment]
Maybe related to the fact that there is still no tool to generate them on the fly?

**Comment by kytrinyx** [comment]
Configlet has a `uuid` command that generates new uuids. Is that not what you're looking for?

**Comment by NobbZ** [comment]
Oh, I missed the introduction then… You've never seen me here ;)

**Comment by patricksjackson** [comment]
Those were pushed after @kytrinyx generated the UUIDs but before that PR was merged, hence the mixup. I don't know anything about working with configlet at the moment.

Looking...

**Comment by kytrinyx** [comment]
> I don't know anything about working with configlet at the moment.

This is particularly badly documented... and a bunch of things are in flux. Once it's settled a bit I'll write up something nice and post about it to the discussions repo.
