### ISSUE TITLE
Initial hello-world make fails under Debian stretch.

### ISSUE THREAD

**Issue by sjfloat** [exercism/cpp#154]
Apparently something is lacking in my environment. I'm happy to provide whatever details might be helpful.

```
Linux dc7e4195fb83 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1 (2016-12-30) x86_64 GNU/Linux
>cmake -G "Unix Makefiles"

-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   unit_test_framework
--   date_time
--   regex
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dev/exercism/cpp/hello-world
>make

[35m[1mScanning dependencies of target hello-world[0m
[ 50%] [32m[1mLinking CXX executable hello-world[0m
CMakeFiles/hello-world.dir/hello_world_test.cpp.o: In function `test_hello::test_method()':
hello_world_test.cpp:(.text+0x3be): undefined reference to `hello_world::hello[abi:cxx11]()'
collect2: error: ld returned 1 exit status
CMakeFiles/hello-world.dir/build.make:97: recipe for target 'hello-world' failed
make[2]: *** [hello-world] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/hello-world.dir/all' failed
make[1]: *** [CMakeFiles/hello-world.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by sjfloat** [comment]
[typescript.txt](https://github.com/exercism/cpp/files/1347411/typescript.txt)

**Comment by patricksjackson** [comment]
Looks like you have everything set up correctly. What you need to do is define a `hello_world::hello()` function, see this line:
```
hello_world_test.cpp:(.text+0x3be): undefined reference to `hello_world::hello[abi:cxx11]()'``
```
The exercises here don't compile until you define the header file in the way the test expects, and then you also need to define the actual function in a *.cpp file (hello_world.cpp in this case).

**Comment by sjfloat** [comment]
Thanks for responding so quickly!

Must it be function? My understanding is that the test is expected to be implementable with just a header. Here is the contents of the supplied hello_world.h:

```
#if !defined(HELLO_WORLD_H)
#define HELLO_WORLD_H

#include <string>

namespace hello_world {

std::string hello();

}

#endif
```

**Comment by sjfloat** [comment]
OK, I withdraw my silly issue. It seems that this initial header fails initially by failing to compile.

Thanks!

**Comment by patricksjackson** [comment]
No problem. Note that the other exercises usually don't include the header either, the expectation is to look at what the test is expecting to use and create your own header and source file, so nothing will compile at first :)

Everything is more or less a similar format (using a namespace based on the exercise name and then a function or class defined in it) so if you are very new to cpp you can mostly copy the correct format from the hello world exercise and work from there.

**Comment by sjfloat** [comment]
Well, I surely should have looked at the code before opening an issue.:/

Thanks for being so responsive.

**Comment by patricksjackson** [comment]
Happy to help, just lucky I happened to be around today.

In the future, the Exercism gitter channels might be a faster way to ask for help. Somebody there is usually familiar enough to help with issues or to recommend creating an issue here.

https://gitter.im/exercism/home
