### ISSUE TITLE
inconsistency in the triangle exercise

### ISSUE THREAD

**Issue by antony-jr** [exercism/cpp#167]
We all know that an equilateral triangle is also an isosceles, from 8th grade.
**But** , In the exercise there is only one function to return the kind of the triangle which does'nt make   
any sense.

**I would be happy to work on this**

And please consider adding a issue template offered by **github** , It makes it easier for you guys.

**Anyways , you guys are doing a great job , keep up your job ❤️**

**Comment by NobbZ** [comment]
Take a look at [the canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/triangle/canonical-data.json), it does test for attributes `equiliteral`, `isosceles`, and `scalene` instead for a single method which returns the most specific classification.

**Comment by antony-jr** [comment]
okay , got it.

**Comment by NobbZ** [comment]
Why are you closing without a PR? As I understood your issue, you basically
complaining that the exercises implementation in CPP and the canonical data
have diverged. So this issue is legit.

Disclaimer: I'm not a maintainer of CPP, but only watching the repositories
issues.

Antony Jr <notifications@github.com> schrieb am Do., 23. Nov. 2017, 16:50:

**Comment by antony-jr** [comment]
a little misunderstanding!

**Comment by antony-jr** [comment]
This issue is fixed in #168

**Comment by antony-jr** [comment]
@NobbZ Its been long and no one has responded to the pull request ? Is this track dead ? or temporarly inactive.

**Comment by LegalizeAdulthood** [comment]
I'll take a look at it, but the current solution appears to satisfy the problem description as written, so what exactly is the problem with the current solution?

**Comment by antony-jr** [comment]
@LegalizeAdulthood as stated in the issue description... 
> We all know that an equilateral triangle is also an isosceles, from 8th grade.
But , In the exercise there is only one function to return the kind of the triangle which does'nt make
any sense.

From the [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/triangle/canonical-data.json)  line 98 , equilateral triangles are also isosceles. But a single function will not statisfy that. 

You can see it from the code...
```
    if (a == b && b == c) {
        return equilateral;
    }
    if (a == b || b == c || a == c) {
        return isosceles;
}
```

and the test are also too old and does not follow the canonical data.
look here...

```
BOOST_AUTO_TEST_CASE(isosceles_triangles_have_in_fact_exactly_two_sides_equal)
{
    BOOST_REQUIRE_EQUAL(triangle::isosceles, triangle::kind(10, 10, 2));
}
```

> isosceles_triangles_have_in_fact_exactly_two_sides_equal

Thats debatable and the specification mentioned that we keep it as atleast and not exactly two sides equal... 

From problem specification... 

> An isosceles triangle has at least two sides the same length. (It is sometimes specified as having exactly two sides the same length, but for the purposes of this exercise we'll say at least two.)

So thats why I think this exercise has to be fixed asap... :+1:

**Comment by LegalizeAdulthood** [comment]
Where in the problem description does it say that I must report an equilateral triangle as also an isosceles triangle?  It doesn't.  The canonical data assumes a property-based approach, but that is an assumption of the data, not a requirement of the problem.  If you think a property-based approach is required for this problem, then we need to open an issue on the problem statement and have it adjusted.

**Comment by antony-jr** [comment]
@LegalizeAdulthood Take a look at the **C** Track , https://github.com/exercism/c/blob/master/exercises/triangle 

Refer this too... https://github.com/exercism/c/pull/121 , Said by ``` @patricksjackson ```
> Ok, I see you just grabbed the solution from the xcpp track (which is good, much of that code can be shared). Unfortunately it seems that solution is out of date with the canonical test cases.

>The idea behind the change is that since triangles can be multiple types (e.g. every Equilateral triangle is also Isosceles) it makes more sense to test Triangle properties rather than determining their type.

>What you need to do then is to rewrite it to use 3 different functions that all return a bool: is_equilateral, is_isosceles, and is_scalene. Then test them with the tests in the canonical json.

**Comment by LegalizeAdulthood** [comment]
You keep referring to the canonical data as requirements.  If you think it *is* a requirement, then the problem description is wrong.

**Comment by antony-jr** [comment]
> You keep referring to the canonical data as requirements. If you think it is a requirement, then the problem description is wrong.
As I read the description a triangle is one of those types. In other words, equilateral is a special case of isosceles.

Then we should change the problem description before closing this issue.  Thank you for your Time! :+1:

**Comment by LegalizeAdulthood** [comment]
You seem to conclude that the canonical test data is imposing a requirement on the problem and that if there is some test data suggested for a particular style of solution, then the problem statement must be updated to reflect an enforcement of this particular style of solution.

I disagree.  The canonical data was generated with a property-based solution in mind, but the problem statement doesn't demand a property-based solution.
