### ISSUE TITLE
Setting up C++ Env, Boost, 1st exercise

### ISSUE THREAD

**Issue by matiaslavista** [exercism/cpp#176]
Hi All,

I'm on  Ubuntu 16.04.4 LTS
I was able to download the client and download the first exercise, and was having trouble compiling it. 

I did eventually find my way around to downloading boost 1.66 from source and building it (it was quite frustrating, but hey maybe thats on me [about 30 min]). Then cmake wouldn't understand the version that I had, (kept saying my version was > 1.59) and I went and edited CMakeCache.txt

However I just changed somethings until I got it to compile, I changed these two:
'''
//Path to a file.
Boost_INCLUDE_DIR:PATH=/home/ubuntu/Downloads/boost_1_66_0
//No help, variable specified on the command line.
BOOST_LIBRARYDIR:PATH=/home/ubuntu/Downloads/boost_1_66_0/lib
'''
I did get it to compile with some errors, there are  definitely other settings here that have me worried like:
'''
//The directory containing a CMake configuration file for Boost.
Boost_DIR:PATH=Boost_DIR-NOTFOUND
'''

Anyway, my current hello_world.cpp looks like this:
`
#include "hello_world.h"
#include <iostream>
using namespace std;

string hello_world::hello(){
    string s = "Hello, World!";
    return s;
}
`
And when I run make, I get the following error:

```
 CMake Warning at /usr/share/cmake-3.5/Modules/FindBoost.cmake:725 (message):
  Imported targets not available for Boost version 106600
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:763 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:1332 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:14 (find_package)


CMake Warning at /usr/share/cmake-3.5/Modules/FindBoost.cmake:725 (message):
  Imported targets not available for Boost version 106600
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:763 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:1332 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:14 (find_package)


CMake Warning at /usr/share/cmake-3.5/Modules/FindBoost.cmake:725 (message):
  Imported targets not available for Boost version 106600
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:763 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:1332 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:14 (find_package)


-- Boost version: 1.66.0
-- Found the following Boost libraries:
--   unit_test_framework
--   date_time
--   regex
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/exercism/cpp/hello-world/build
[ 33%] Linking CXX executable hello-world
CMakeFiles/hello-world.dir/hello_world_test.cpp.o: In function `__static_initialization_and_destruction_0(int, int)':
hello_world_test.cpp:(.text+0x728): undefined reference to `boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case*, boost::unit_test::decorator::collector&, unsigned long)'
CMakeFiles/hello-world.dir/hello_world_test.cpp.o: In function `boost::unit_test::make_test_case(boost::function<void ()> const&, boost::unit_test::basic_cstring<char const>, boost::unit_test::basic_cstring<char const>, unsigned long)':
hello_world_test.cpp:(.text._ZN5boost9unit_test14make_test_caseERKNS_8functionIFvvEEENS0_13basic_cstringIKcEES8_m[_ZN5boost9unit_test14make_test_caseERKNS_8functionIFvvEEENS0_13basic_cstringIKcEES8_m]+0xc0): undefined reference to `boost::unit_test::test_case::test_case(boost::unit_test::basic_cstring<char const>, boost::unit_test::basic_cstring<char const>, unsigned long, boost::function<void ()> const&)'
CMakeFiles/hello-world.dir/hello_world_test.cpp.o: In function `bool boost::test_tools::tt_detail::check_frwd<boost::test_tools::tt_detail::equal_impl_frwd, char [14], std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(boost::test_tools::tt_detail::equal_impl_frwd, boost::unit_test::lazy_ostream const&, boost::unit_test::basic_cstring<char const>, unsigned long, boost::test_tools::tt_detail::tool_level, boost::test_tools::tt_detail::check_type, char const (&) [14], char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*)':
hello_world_test.cpp:(.text._ZN5boost10test_tools9tt_detail10check_frwdINS1_15equal_impl_frwdEA14_cNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEbT_RKNS_9unit_test12lazy_ostreamENSC_13basic_cstringIKcEEmNS1_10tool_levelENS1_10check_typeERKT0_PSH_RKT1_SO_[_ZN5boost10test_tools9tt_detail10check_frwdINS1_15equal_impl_frwdEA14_cNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEbT_RKNS_9unit_test12lazy_ostreamENSC_13basic_cstringIKcEEmNS1_10tool_levelENS1_10check_typeERKT0_PSH_RKT1_SO_]+0x150): undefined reference to `boost::test_tools::tt_detail::report_assertion(boost::test_tools::assertion_result const&, boost::unit_test::lazy_ostream const&, boost::unit_test::basic_cstring<char const>, unsigned long, boost::test_tools::tt_detail::tool_level, boost::test_tools::tt_detail::check_type, unsigned long, ...)'
collect2: error: ld returned 1 exit status
CMakeFiles/hello-world.dir/build.make:123: recipe for target 'hello-world' failed
make[2]: *** [hello-world] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/hello-world.dir/all' failed
make[1]: *** [CMakeFiles/hello-world.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```
======================================
I have been able to commit the exercise, but I want it to actually pass the test so I can make sure my configuration is correct. Please let me know what I'm missing.

Thank you!

**Comment by LegalizeAdulthood** [comment]
For ubuntu you shouldn't need to build boost from scratch yourself.  Did you attempt to install it by apt-get?  See http://exercism.io/languages/cpp/installation

**Comment by matiaslavista** [comment]
I tried that ppa and downloaded a ton of stuff, with 
'sudo apt-get -qq -d update'
and then
'sudo apt-get install boost1.60'
says unable to locate package, same for boost 1.66

I guess what you are saying is that I should look for a ppa that has boost, I'll go do that ...
The one problem I have is I know believe I have 2 versions of boost already installed, 1.58 1.66

Anyway, Do you think that the above error is due to a poorly installed Boost?

**Comment by NobbZ** [comment]
The PPA you need to add is listed in the installation instruction for boost.

**Comment by matiaslavista** [comment]
Hi NobbZ, I did indeed install the samuel-bachmann ppa, and I recieved the errors shown above,
i.e. I get the error that the package doesn't exist .

I followed the instructions straight forward and when that ppa did not work, I looked for the source version and compiled it.

Its still not clear ot me if the above error is due to a misconfiguartion of boost, and I can't find a way of installing boost >1.58 v from apt-get

**Comment by LegalizeAdulthood** [comment]
I can reproduce that getting even boost 1.60 from that PPA no longer works :-(

This may all be the final nail in the coffin for the boost and force the switch to catch.

**Comment by matiaslavista** [comment]
Nails and coffins, how do I setup boost in the meantime? :)

**Comment by NobbZ** [comment]
You could use arch or Gentoo flavored distributions in a VM/Container.

The PPA is for trusty (14.04 LTS) only. I wasn't able to find a PPA quickly that provides 1.59+ for Xenial.

**Comment by LegalizeAdulthood** [comment]
@matiaslavista If we can't find a PPA with a prebuilt binary, then you're stuck compiling from source unfortunately.  See if you can follow the instructions on the boost website for [getting started with linux](http://www.boost.org/doc/libs/1_66_0/more/getting_started/unix-variants.html#or-build-custom-binaries).

**Comment by exklamationmark** [comment]
@matiaslavista: I recently went and setup Boost 1.67.0 from source.
The steps are here: https://gist.github.com/exklamationmark/90325a57418ab1cfac1aaac1053fce5a, in case you are still having problem.

**Comment by patricksjackson** [comment]
We've removed our dependency on Boost, see #233. For Ubuntu 16.04 we support using only the compiler toolchain and cmake available in the repos, so this should be much easier now. See the new docs.
