### ISSUE TITLE
error when running make

### ISSUE THREAD

**Issue by S4G4R** [exercism/cpp#177]
So I've set up my environment, I'm using Atom to do the exercises but I'm stuck on the first one. (C++)
I've installed cmake and boost, using Homebrew on Mac. I created a 'build' folder inside the hello-world folder and I ran _cmake .._ inside it, which generated the required files.

Now I'm new to TDD, but from what I can see all I have to do to run the tests is run _make_ in the terminal? When I do so, it spits out a huge error message, which I'm attaching here.

I'm not sure if I'm just being stupid or something really is wrong, so please help me. It seems to be something about missing libraries.

[error.txt](https://github.com/exercism/cpp/files/1800112/error.txt)

**Comment by patricksjackson** [comment]
This looked like it was some error building boost. We've removed our dependency on Boost, see #233. See the new docs for new directions.
