### ISSUE TITLE
Adding more reading resources to begin with C++?

### ISSUE THREAD

**Issue by exklamationmark** [exercism/cpp#180]
Hi there,

I recently started the C++ track. While I eventually get things to work, it still feel like there's a lot missing knowledge that's not mentioned in the [install](http://exercism.io/languages/cpp/installation) and [unit testing](http://exercism.io/languages/cpp/tests) guides.

For me the harder part of learning to use C++ is about understanding how to use the tools, compiler & how to read error messages. It's hard to get started if you can't get a hello-world program & unit tests to work.

Before even writing the `hello_world.cpp`, I think these knowledge could be useful:
1. Some rough understanding on how C++ code are compiled & linked (source -> object files, linking` with stdlib & boost, etc). For example, something similar to [this answer on StackOverflow](https://stackoverflow.com/questions/3322911/what-do-linkers-do#answer-3323000)
2. An intro to `make` and `Makefile`. Intro to `cmake` can come after that
3. A more detailed guide on how to install `Boost`, which hopefully will be smoother if people have read (1) and (2)

What do you think?

**Comment by Llcoolsouder** [comment]
I agree that an intro to CMake is in order. I do all the building and testing with
```
mkdir build
cd build
cmake -DEXERCISM_RUN_ALL_TESTS=ON ..
cmake --build .
```
which is fairly common.

These lines should probably somewhere on the unit testing page under CMake.
