### ISSUE TITLE
Add more compilation flags

### ISSUE THREAD

**Issue by AlexLeSang** [exercism/cpp#193]
I think that compile flags for exercises should contain at least '-Wall', maybe '-Wextra' and '-Wpedantic' and even '-Werror'. That would provide students with better diagnostics from the compiler and avoid common mistakes.

**Comment by patricksjackson** [comment]
I agree with this. It's what we've done on the C track as well. This is the list we use there:

```
CFLAGS += -g
CFLAGS += -Wall
CFLAGS += -Wextra
CFLAGS += -pedantic
CFLAGS += -Werror
```

@AlexLeSang would you like to make the change? It should be a change to [this line](https://github.com/exercism/cpp/blob/6e2a2693ca7a6d609396bd61699baf73f6087247/exercises/allergies/CMakeLists.txt#L18) that needs to be changed in every CMakeLists.txt file in the exercises folder.

**Comment by KevinWMatthews** [comment]
Do you find `-Werror` to be a useful teaching tool? Personally I feel that it tends to disrupt one's workflow and it can be frustrating to be at the mercy of a pedantic compiler.

Having said that, it may be more important to force students to resolve all issues. Warnings are easy to ignore, especially if you don't clean the project.

**Comment by patricksjackson** [comment]
I have no strong opinions on using `-Werror` here, it's useful for me (usually), and there are not many false positives with just all/extra/pedantic enabled. Generally those flags only pop up things that really should be fixed, or that actually are bugs int he code.

I admittedly don't teach enough to know if it's helpful for beginners, so I am totally open to other opinions.

**Comment by KevinWMatthews** [comment]
Thinking over this again, I wonder if I'm projecting my experience with C warnings on to C++. I'm happy to defer to others.

@AlexLeSang are you excited to add this? If so, by all means. If not, I might give it a go myself - I should have time this weekend.

**Comment by AlexLeSang** [comment]
Yes, I am very excited to do this and I will do it this weekend. 

In my experience working with less experienced colleagues, it is always better to promote a warning  to an error and pedantic compiler can teach a lot.

**Comment by KevinWMatthews** [comment]
@AlexLeSang For sure. Enjoy!

**Comment by patricksjackson** [comment]
These are now supported in the cmake files. Thanks!
