### ISSUE TITLE
Need help with the setup.

### ISSUE THREAD

**Issue by Voksel** [exercism/cpp#200]
I tried following the steps given in exercism.io website about installing c++ but I am not able to understand what I am suppost to do. I installed visual basic 2017, cmake and boost but have no idea how to continue with the steps.

**Comment by kmce25** [comment]
Same, instructions are not good for newbies. Did you ever get it figured out?

**Comment by Voksel** [comment]
Nope i didn't i started using codeacademy.com instead. It is a great site
but you have to pay to access more advanced courses. There is a 7 day trial
which you can try to see if you like it!
