### ISSUE TITLE
Stylistic udpate to CMake 

### ISSUE THREAD

**Issue by KevinWMatthews** [exercism/cpp#205]
Do you think students use Exercism's CMakeLists.txt files as a model? If so, I'd like to propose a few stylistic changes to promote what I hope are best practices.

I've made a [Gist](https://gist.github.com/KevinWMatthews/12f78889c3a60d9281f19e10de9c6919/revisions?diff=split) illustrating the before and after.

The changes are:
  * Set compile flags using `set_target_properties()` instead of `CMAKE_CXX_FLAGS`
  * Link against libraries using a namespace (e.g. `Boost::unit_test_framework`) instead of paths defined by CMake variables
  * Set compile definitions per target using `target_compile_defintions()` instead of per directory with `add_definitions()`
  * Actually run tests after every build by using `add_custom_target()` instead of `add_custom_command()`

Note that a few of these changes would require changing the version of CMake, which may not be a possibility.

For the sake of brevity, I'll give some of the rationale for each change in a separate comment.

**Comment by patricksjackson** [comment]
Ok, I didn't see this until after I responded to #189 and hinted that I would really like it if someone made this update to the CMake files.

This is awesome, and exactly what I wanted. I'll need to spend a little time to review these changes before I could merge them, but I want to take them. I'll note here again that the CMake version update to 3.1.3 shouldn't be an issue, as it's older than what is in Ubuntu 16.04

I love the changes, and thanks for including the rationale for the changes too. I am not one of the chosen few who understands CMake, so this really helps me understand the changes.

You were right to keep the `-W` flags specific to gcc and clang, the flags are different on other platforms (they actually vary between gcc and clang as well, but those are kept common (though not with identical behavior) for portability between those two AFAIK). My only hope there would have been if CMake had a facility to specificy a warning level across different compilers.

**Comment by KevinWMatthews** [comment]
Sounds good. Take some time to digest and feel free to ask for clarification.

I don't think that there is any portable way to specify the compiler's warning level. It looks to be an [open issue](https://gitlab.kitware.com/cmake/cmake/issues/17743), actually.

I haven't yet tried this patch in the context of the complete build system - only individual packages on my system. I'm curious see if it works under exercism's setup. Hmmm, it looks like `travis.yml` specifies `trusty`, which [ships with CMake 2.8.12](https://packages.ubuntu.com/trusty/cmake) by default. I think? On closer inspection, it looks like there is a `cmake3` package that [provides CMake 3.5.1](https://packages.ubuntu.com/trusty/cmake3). I'll investigate further with a few Docker containers to make sure CMake can be installed easily.

**Comment by KevinWMatthews** [comment]
Looks like there are improvements that can be made to the [high-level CMakeLists.txt](https://github.com/KevinWMatthews/cpp/commit/dbcc1aa1123652cee98797398005da23673a8420#diff-af3b638bc2a3e6c650974192a53c7291). 

The rationale:
- Rather than manually running CMake within CMake, let CMake run itself by using the `add_subdirectory()` command. CMake will enter this subdirectory, search for `CMakeLists.txt`, and run with the appropriate options and flags. 
- Configure `EXERCISM_RUN_ALL_TESTS` as an `option` rather than passing it manually. This exposes the option to the user, allowing it to be easily configured from a high-level tool such as `ccmake`, `cmake-gui`, or from the command line. You can verify that this flag is set using the above tools or by running `cmake -L`. Not that we'd want to disable the option in this case; this is an attempt at best practice.
- There is no need to configure a custom `ALL` target. Each subdirectory's `CMakeLists.txt` does this automatically when `add_executable()` is run.

**Comment by KevinWMatthews** [comment]
I've created a pull request for your inspection and digestion, at your leisure. It does *not* update the CMake standard because this actually breaks the Clang build (!) - see #189.

**Comment by patricksjackson** [comment]
Closing this after merging the changes in #209. Thanks @KevinWMatthews !

**Comment by KevinWMatthews** [comment]
Awesome! My pleasure.
If you encounter issues, feel free to tag me. I can use an excuse to learn more about CMake.
