### ISSUE TITLE
Unable to debug code while unit tests are failing

### ISSUE THREAD

**Issue by sevi5** [exercism/cpp#214]
I setup exercism according to the guides on the websites. I'm currently trying to do the hamming exercise and I wanted to use the Visual Studio debugger to step through my code in order to see variable values. Unfortunately I'm not able to debug my application because of build errors that come from the unit tests.

Is this the normal behaviour of the cpp exercises? What can I do to enable debugging my code with data being passed from the unit tests?

**Comment by NobbZ** [comment]
It's just normal that you can not debug a program that doesn't compile and hasn't to do anything with the tests.

For debugging you need to run, to run you need to compile, that's just how things work.

Fix the compilation errors, then you should be able to debug.

**Comment by patricksjackson** [comment]
@sevi5 You will need to get it compiling first before you can debug it. If the build errors are coming from unit tests that you aren't trying to debug (e.g. a unit test testing functionality that you haven't implemented yet) you can comment or `#ifdef` out the tests that don't compile.

**Comment by sxiomar** [comment]
sevi1603 is right and you people trying to point fingers instead of help are wrong. A test failure, like producing actual!=expected, is not debuggable. This was not the case on the c track and is very annoying.
