### ISSUE TITLE
Anagram: Tests need an update

### ISSUE THREAD

**Issue by tqa236** [exercism/cpp#218]
I find that the second and the last test cases of Anagram exercise are nearly the same, only a minor difference about the order of string. Is it a duplication or are there any reasons to include both tests?
Also, the tests here are quite behind the problem specifications repo.

Here are the 2 test cases I mentioned:

```
BOOST_AUTO_TEST_CASE(detects_simple_anagram)
{
    auto subject = anagram::anagram("ant");
    auto matches = subject.matches({"tan", "stand", "at"});
    vector<string> expected{"tan"};

    BOOST_REQUIRE_EQUAL_COLLECTIONS(expected.begin(), expected.end(), matches.begin(), matches.end());
}

BOOST_AUTO_TEST_CASE(matches_accepts_string_arguments)
{
    auto subject = anagram::anagram("ant");
    auto matches = subject.matches({"stand", "tan", "at"});
    vector<string> expected{"tan"};

    BOOST_REQUIRE_EQUAL_COLLECTIONS(expected.begin(), expected.end(), matches.begin(), matches.end());
}
```

**Comment by patricksjackson** [comment]
From the name of the test case it looks like it was originally intending to test that it accepted multiple argument types, but the tests as they exist today are unchanged from when they were initially written in 2014.

So in short, I don't know why that's the case, and the tests need an update to the latest problem specifications - https://github.com/exercism/problem-specifications/blob/master/exercises/anagram/canonical-data.json

@tqa236 if you'd like to do the update you're welcome to.
