### ISSUE TITLE
Consider removing dependency on Boost::date_time

### ISSUE THREAD

**Issue by KevinWMatthews** [exercism/cpp#224]
Most exercises don't use `Boost::date_time`, but it is required for all exercises.
A quick search shows that it is currently used in:
  * gigasecond
  * meetup

Is it possible and reasonable to use standard library functions instead?

We could remove the `Boost::date_time` dependency for all but these two exercises, but it may introduce a maintenance headache for marginal gains.

**Comment by patricksjackson** [comment]
Both of those are in the C track using only standard tools, but doing that changes the exercises significantly (for the worse I think). I haven't paid too much attention to what exercises are 'core' or extra, but if we switch them I think we should hand all complexity to the user, make sure they aren't 'core', and potentially encourage library use. We should probably also run the changes by the mentors before merging.

Also, see #159. One of the patches removes it from gigasecond, though at the time I decided to leave meetup alone.

I think there isn't much benefit to removing it from the shared CMake file until we can remove it from all of them. It's not really a huge difficulty to install a second boost library once we've already installed the unit test suite.

This would be good to have. I initially worked on #159 to remove all of Boost at once, but that's a bit too impractical. There are too many of these smaller dependencies we have other than the unit test suite. I will setup a tracking issue at some point soon to track the Boost removal work.

There are planned improvements to std::chrono that should make them a little easier to do with std, but they will go into C++20 so we obviously can't use that. The C track just to see how bad it currently is:
For meetup, the complexity is left to the user which results in this - https://github.com/exercism/c/blob/master/exercises/meetup/src/example.c
For gigasecond, we handled all the complexity in the test suite for some reason - https://github.com/exercism/c/blob/master/exercises/gigasecond/test/test_gigasecond.c

**Comment by KevinWMatthews** [comment]
Good points all around. You don't realize just how much Boost does for you until you try to do it manually.

I recall Gigasecond being fairly early in the track. Yes, look's like it's the third core exercise (Hello World being the first).

It seems a bit of a shame to drop so much detail on the students so early in the track, but that may just be how C++ is. And you do get quite a few side exercises after completing the first core exercise. But that may be a better question for the mentors, as you suggest.

Feel free to close this issue in favor of a future issue tracking Boost as a whole.

**Comment by patricksjackson** [comment]
As an update, I've now switched out Gigasecond in the core tracks, so this will be somewhat less of an issue. 

To close this issue, let's add descriptions appropriately for Gigasecond and Meetup that explain having to install Boost. We'll need to deal with that once they've moved to Catch.

**Comment by patricksjackson** [comment]
I'm going to close this. We do have this dependency still and we don't have full descriptions of installation instructions for Boost in gigasecond and meetup, but I expect that if students have issues with it they'll just skip those exercises. For the majority of students it's literally a Google search and a single command away.

If there are problems in the future we can consider trying to improve the documentation or removing this. I don't know of a header only date time library unfortunately, and we need to wait a long time for C++20 to get std facilities capable of doing this reasonably.
