### ISSUE TITLE
c++ phone number mistake.

### ISSUE THREAD

**Issue by ViralTaco** [exercism/cpp#227]
Hi,

Here: [https://github.com/exercism/cpp/tree/master/exercises/phone-number](https://github.com/exercism/cpp/tree/master/exercises/phone-number) 
you say

> The format is usually represented as
> 
> ```text
> (NXX)-NXX-XXXX
> ```
> 
> where `N` is any digit from 2 through 9 and `X` is any digit from 0 through 9.

However in the tests : 
`BOOST_REQUIRE_EQUAL("1234567890", phone.number());`

The problem: `1` isn't a digit **from** `2` through `9`

Thank you for your time

**Comment by KevinWMatthews** [comment]
Well, that is a contradiction, isn't it?

Good catch - need to look into this.

**Comment by KevinWMatthews** [comment]
Looks like the [problem description](https://github.com/exercism/problem-specifications/blob/master/exercises/phone-number/description.md) and [problem specification](https://github.com/exercism/problem-specifications/blob/master/exercises/phone-number/canonical-data.json) have evolved but our [test suite](https://github.com/exercism/cpp/blob/master/exercises/phone-number/phone_number_test.cpp) has not.

**Comment by ViralTaco** [comment]
Thanks for replying. 
I can look at implementing the tests from the problem spec but I'm not sure when I'll be able to do it. :/ 
I'll try to remember not to forget.

**Comment by ViralTaco** [comment]
Hey @KevinWMatthews 
I got [this](https://github.com/ViralTaco/cpp/tree/exercism_phone_cpp/exercises/phone-number)
please tell me if it's ok to make a pull request (especially since it's on the master branch, don't wanna f that up)

**Comment by KevinWMatthews** [comment]
Hey @ViralTaco ,

Thanks for your help. Yes, it's typically safe to make a pull request. Your changes will end up on the master branch of the main exercism repo, but they don't go directly there - the maintainers have to merge them first. So hack away!

Also, you can easily reference other issues or pull requests using a '#'. Something like this: #229 . Try it out - it's a nice GitHub feature.

**Comment by ViralTaco** [comment]
Nice, thank you for the tip.

**Comment by patricksjackson** [comment]
Closed by #230
