### ISSUE TITLE
How to run all tests without editing test.cpp?

### ISSUE THREAD

**Issue by hickford** [exercism/cpp#243]
Following https://github.com/exercism/cpp/blob/master/exercises/leap/README.md to run all the tests for an exercise, I edit eg. `leap_test.cpp` to move or delete the line `#if defined(EXERCISM_RUN_ALL_TESTS)`.

Is it possible to run all the tests without editing `leap_test.cpp`? This would be more convenient for me.

I tried `make EXERCISM_RUN_ALL_TESTS=1` but it still only ran one test.

* * *

If it's relevant, my setup following https://github.com/exercism/cpp/blob/master/docs/TESTS.md

```
mkdir build
cd build
cmake -G "Unix Makefiles" ..
cd ..
make
```

**Comment by siebenschlaefer** [comment]
You could tell `cmake`  to define `EXERCISM_RUN_ALL_TESTS` on the command line:  
```
cmake -DEXERCISM_RUN_ALL_TESTS=1 ..
```

Also, if you want to run `clang-tidy` you might also want to add `-DCMAKE_EXPORT_COMPILE_COMMANDS=1` to that.

**Comment by hickford** [comment]
Thank you, that worked perfectly
