### ISSUE TITLE
Can't advance to next exercise on C++ track

### ISSUE THREAD

**Issue by ehom** [exercism/cpp#262]
First of all, thank you for exercism. I'm very grateful for it.

Anyway, I'm **stuck** on exercise 2 on the c++ track.

My solution was approved before the update. Then I updated my solution to use both (.h and .cpp) files.

Can you help me figure out what I'm doing wrong?

Thanks!

**Comment by NobbZ** [comment]
After a mentor has approved the solution, you need to click the complete button before you can advance.

**Comment by ehom** [comment]
Thx for the quick response. I will wait for a mentor's approval.

**Comment by NobbZ** [comment]
But you said, a mentor already approved your solution.

**Comment by ehom** [comment]
it was approved previously. Then after a long time, i visited the problem/solution page and it said that my solution on an older version. So I updated my solution based on the new requirement.

**Comment by ehom** [comment]
Just checked. My solution was originally published to the community on: 

> Published at Jul 13 2018

**Comment by NobbZ** [comment]
Okay, then the next exercise should be available, if not, please show a screenshot of your current dashboard and a screenshot of the exercise that is shown as last available in the dashboard.

Please also provide the URL to the latter.

**Comment by ehom** [comment]
<img width="1681" alt="Screen Shot 2019-04-11 at 1 01 44 AM" src="https://user-images.githubusercontent.com/796780/55940715-86e85900-5bf5-11e9-86be-901c061474e0.png">

**Comment by NobbZ** [comment]
@ihid, as the initial publishing date was about the big migration, and then an update of the code was done, can this be related to exercism/exercism#4741

**Comment by iHiD** [comment]
For clarity, there was no approval before the migration, so the solution wasn't approved before then. I'll try and look at the various issues you've both raised about this today or tomorrow. Sorry for the delay - I'm having a very busy period in the day job atm.

**Comment by patricksjackson** [comment]
As an additional data point, we recently swapped the third core exercise out, which is what is not being unlocked here. It was Gigasecond, but we demoted that to non-core and replaced it with Reverse-String.

**Comment by iHiD** [comment]
Ah. I have to run a script in these situations. Please slack me to let me
know this in future. I'll run it now. Thanks!

**Comment by patricksjackson** [comment]
Closing this since I think it's resolved. @ehom please reopen this if you're having issues.

I've added a note for us here to not break this again. Thanks!
