### ISSUE TITLE
No header file

### ISSUE THREAD

**Issue by evanricard** [exercism/cpp#298]
Hey Exercism, I love all of the tracks I have joined so far however the C++ one seems a bit curious. Forgive me, I am noob, but are the C++ exercise files supposed to include a .h file? Every other track I have tried seems to have the entire structure available and you have to follow along in a koan-like pattern. I figured I would ask because the "Hello, World!" example comes with a header file but the rest of the projects do not. In any event, thanks a lot!! 

Edit: I am realizing I do not have a .cpp as well and I only get the *_test.cpp, catch.hpp, and tests-main.cpp files. Thanks!

**Comment by patricksjackson** [comment]
Yes, that's expected. I believe some of the exercises have header files to
be clearer about what's being asked (or for Hello World to teach the
basics), but for the most part the header file definition is meant to be
part of your solution. Choosing the right data types for the arguments and
return values can be very important parts of the solution in C++.

>

**Comment by evanricard** [comment]
Ok, thanks @patricksjackson!
