### ISSUE TITLE
Create stub files for all exercises

### ISSUE THREAD

**Issue by kytrinyx** [exercism/cpp#300]
We have decided to require all file-based tracks to provide stubs for their exercises.

The lack of stub file generates an unnecessary pain point within Exercism, contributing a significant proportion of support requests, making things more complex for our students, and hindering our ability to automatically run test-suites and provide automated analysis of solutions.

We believe that it’s essential to understand error messages, know how to use an IDE, and create files. However, getting this right as you’re just getting used to a language can be a frustrating distraction, as it can often require a lot of knowledge that tends to seep in over time. At the start, it can be challenging to google for all of these details: what file extension to use, what needs to be included, etc. Getting people up to speed with these things are not Exercism’s focus, and we’ve decided that we are better served by removing this source of confusion, letting people get on with actually solving the exercises.

The original discussion for this is at https://github.com/exercism/discussions/issues/238.

Therefore, we’d like this track to provide a stub file for each exercise.

- If this track already provides stub files for all exercises, please close this issue.
- If this track already has an open issue for creating stubs, then my apologies. Please close one as a duplicate.
- Otherwise, please respond to this issue with useful details about what needs to be done to complete this task in this track so that people who are not familiar with the track may easily contribute.

**Comment by marko213** [comment]
For the exercises I solved, I ended up writing a small bash script to download the exercise, generate boilerplate (stub) and build it for me.

The following is what gets written to the files (with `$n` being the exercise name, with `_` instead of `-`):

`${n}.h`:

```C++
#ifndef __${n^^}_H__
#define __${n^^}_H__

#define EXERCISM_RUN_ALL_TESTS

namespace $n {

}

#endif
```

`${n}.cpp`

```C++
#include "${n}.h"

namespace $n {

}
```

This covers most of the cases, but there are some with different namespace names which would need to be fixed manually.

Another thing to consider is header-only solutions - should all exercises be provided a stub with both header and source files or should some arbitrary ones provide only a header? This could cause some students to submit empty stub source files.

**Comment by kytrinyx** [comment]
@marko213 that's really sweet!

> should all exercises be provided a stub with both header and source files or should some arbitrary ones provide only a header? This could cause some students to submit empty stub source files.

Would you elaborate on why students would submit empty stub source files?

> Also, should the stubs provide the empty definitions for the functions / classes with appropriate types in the header?

I don't _think_ we should provide the empty definitions, but if people are getting stuck early on, we could have more elaborate stubs at the start of the track and then reduce what we add to the files as we go along (we do that in some other tracks).

I'd be interested in hearing other opinions, especially from people who have mentored in the C++ track, since they'll probably be familiar with the types of confusion people have.

**Comment by marko213** [comment]
In C++, the solutions are required to provide only a header file - however, most also provide a source file. Header-only solutions are usually found when the problem can be solved in a few lines, though some opt to solve all solutions with a header+source file or all with just a header file.

Now, a generated stub source file shouldn't interfere with anything written in the header file, so it is possible that the unused source file isn't deleted and gets submitted anyway.

**Comment by patricksjackson** [comment]
@kytrinyx Do you have a minimum requirement for the stubs? Just standardizing on the filenames? Or do you need them to compile and fail the first test?

We'll setup all of the boilerplate, but I'd rather not make something that compiles for every exercise unless it's needed for automation. We do that for Hello World, but later exercises should be able to figure that part out themselves.

**Comment by kytrinyx** [comment]
No we don't need it to compile! Just a file with the correct name, and the minimum "boring stuff" in place that can be hard to get right at first when you're unfamiliar with the language and norms.

Thanks so much!

**Comment by siebenschlaefer** [comment]
@marko213  Please use `${n^^}_H` instead of `__${n^^}_H__` for the include guard.  
"*Each identifier that contains a double underscore `__` or begins with an underscore followed by an uppercase letter is reserved to the implementation for any use.*" ([5.10.3.1](https://www.ida.liu.se/~TDDD38/ISOCPP/lex.name.html#3.1))  
"*Each identifier that begins with an underscore is reserved to the implementation for use as a name in the global namespace.*" ([5.10.3.2](https://www.ida.liu.se/~TDDD38/ISOCPP/lex.name.html#3.2))

**Comment by siebenschlaefer** [comment]
> The lack of stub file generates an unnecessary pain point within Exercism, contributing a significant proportion of support requests, making things more complex for our students, [...]

From my own C++ mentoring perspective: Yes, there are some students who submit a standalone program (with `main()`), some who put the solution in the test file and even some who don't know how to read the tests and therefore don't know how to start. But those are only very few.

> [...] and hindering our ability to automatically run test-suites and provide automated analysis of solutions.

Could you elaborate? How does providing a template influence the automated analysis, specifically in C++?

Choosing a signature for your function is an important part of the solution. Take the `reverses-string` exercise: Should I declare `bool reverse_string(std::string str)` or `bool reverse_string(const std::string &str)`? It depends. If I use `std::reverse()` the former is better, but if I use `std::string(str.rbegin(), str.rend())` I should choose the latter.

Could it be enough just to provide a header with an include guard and a `.cpp` file that includes the header?
```cpp
// example.h
#ifndef EXAMPLE_H
#define EXAMPLE_H

#endif
```

```cpp
// example.cpp
#include EXAMPLE_H
```

**Comment by kytrinyx** [comment]
@siebenschlaefer Thanks so much for adding your thoughts here! This is exactly the type of discussion I was hoping we could have, with different trade-offs and different suggestions at how much would be helpful (and why).

> Choosing a signature for your function is an important part of the solution.

Indeed! We're not saying that we need to scaffold up everything.

> Could it be enough just to provide a header with an include guard and a .cpp file that includes the header?

Yes, I think so. I'd like to hear if there are any other thoughts before we lock down an answer to what should go into the stub.

Thanks again for chiming in!

**Comment by patricksjackson** [comment]
> Choosing a signature for your function is an important part of the solution.

^ This is exactly why I asked if it needed to compile, as we really want the student to do that.

I think we should include the namespace in the stubs at least for a few exercises in the core track, if not for all of them.

I think @marko213's stub is very close to what we should have, minus the macro definition :)

``` cpp
// example.h
#ifndef EXAMPLE_H
#define EXAMPLE_H

namespace example {

}

#endif
```
``` cpp
// example.cpp
#include "example.h"

namespace example {

}
```

**Comment by KevinWMatthews** [comment]
Is the [phone_number](https://github.com/exercism/cpp/tree/master/exercises/phone-number) exercise namespaced properly for use with this stub? I don't see any indication of a namespace in our test cases or our example solution.

All other exercises seem to define a namespace. It shouldn't be difficult to add one if we want it.

**Comment by marko213** [comment]
Yes, that is a little weird.

I agree that adding a namespace around it would be a good idea - you can make a PR for that, which'll hopefully be merged before work is completed on the stubs.

**Comment by patricksjackson** [comment]
I agree, that should just be namespaced as well.

**Comment by KevinWMatthews** [comment]
If we apply this to all exercises, will we need to standardize the namespaces that we use? Exercise names usually but don't always correspond to the namespace that we use. For example, the exercise `nucleotide-count` uses the namespace `dna`.

Problem exercises include:

  * [atbash-cipher](https://github.com/exercism/cpp/tree/master/exercises/atbash-cipher)
  * [beer-song](https://github.com/exercism/cpp/tree/master/exercises/beer-song)
  * [binary-search-tree](https://github.com/exercism/cpp/tree/master/exercises/binary-search-tree)
  * [clock](https://github.com/exercism/cpp/tree/master/exercises/clock)
  * [difference-of-squares](https://github.com/exercism/cpp/tree/master/exercises/difference-of-squares)
  * [nth-prime](https://github.com/exercism/cpp/tree/master/exercises/nth-prime)
  * [nucleotide-count](https://github.com/exercism/cpp/tree/master/exercises/nucleotide-count)
  * [roman-numerals](https://github.com/exercism/cpp/tree/master/exercises/roman-numerals)
  * [rna-transcription](https://github.com/exercism/cpp/tree/master/exercises/rna-transcription)

**Comment by marko213** [comment]
I think the namespaces can be left as they are - some would repeat a lot otherwise (like `space_age::space_age` does...).

**Comment by patricksjackson** [comment]
Oh, I thought they were already all the same as the exercise name.

I think they need to be standardized, otherwise this will become a
nightmare to keep them in sync. Since we aren't compiling the stubs we'd
never notice.

(Unrelated, but if this is generated via script it should be checked into
bin/ )
