### ISSUE TITLE
C++ header file naming convention

### ISSUE THREAD

**Issue by KevinWMatthews** [exercism/cpp#305]
Moving [this issue](https://github.com/exercism/exercism/issues/4981) from `exercism/exercism`.

> It's better to change header files extension from .h to .hpp so code editors know that the file is a c++ header. It also helps c++ and c separation.
> https://github.com/lefticus/cppbestpractices/blob/master/03-Style.md#use-hpp-and-cpp-for-your-file-extensions

**Comment by KevinWMatthews** [comment]
Notes:

  * Related discussion in #247 
  * Google style guide on [File Names](https://google.github.io/styleguide/cppguide.html#File_Names).

**Comment by siebenschlaefer** [comment]
Related: [SF.1 of the C++ Core Guidelines](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rs-file-suffix): "*Use a .cpp suffix for code files and .h for interface files if your project doesn’t already follow another convention*"

**Comment by patricksjackson** [comment]
I get that some editors are confused by it, but it is pretty standard convention as @KevinWMatthews and @siebenschlaefer pointed out and it's what we've had here for a long time (though the imported Catch header is hpp now...). It's not worthwhile for us to change it at this point.

Thanks for the suggestion though @parhamrm :)

(As for the links, I prefer to use the https://github.com/isocpp/CppCoreGuidelines linked to by @siebenschlaefer for most things if they have an opinion. The Google style guide has some things in it that are very particular to Google's particular needs. Also TBH it avoids claims of bias.)
