### ISSUE TITLE
plaese add boost install instruction for Gigasecond on cpp track

### ISSUE THREAD

**Issue by fu7mu4** [exercism/cpp#311]
CMakefile.txt in Gigasecond side exercise on cpp track requires external boost library :

```CMakefile.txt
# Locate Boost date_time library
set(Boost_USE_STATIC_LIBS ON)
set(Boost_USE_MULTITHREADED ON)
set(Boost_USE_STATIC_RUNTIME OFF)
find_package(Boost 1.59 REQUIRED COMPONENTS date_time)
```
But no information of boost available on README.md and exercise.
Plaese add boost install instruction for Gigasecond on cpp track.
At least some notation like that "This exercise require boost library."

**Comment by iHiD** [comment]
I've triaged this to cpp.

**Comment by fu7mu4** [comment]
Thanks .

**Comment by KevinWMatthews** [comment]
@iHiD thanks for the transfer!

@fu7mu4 you are right, thanks. We lost this information when we migrated most other exercises to the Catch2 test suite. We should add it back in for specific exercises, but in the meantime you can see the old Boost docs in [this commit](https://github.com/exercism/cpp/pull/267/commits/3864a0141be78223d39decd202e2eb93012a3554).

**Comment by KevinWMatthews** [comment]
#267 removed Boost docs for all exercises. We added comments to the [gigasecond test](https://github.com/exercism/cpp/blob/af78f548f404fedc1f30123e5a6761ec4736346f/exercises/gigasecond/gigasecond_test.cpp#L5) and [meetup test](https://github.com/exercism/cpp/blob/af78f548f404fedc1f30123e5a6761ec4736346f/exercises/meetup/meetup_test.cpp#L5) files telling users to install Boost, but perhaps we should also update the "Getting Started" sections of the respective READMEs?

@patricksjackson thoughts? It's against the spirit of the upgrade to Catch to reimplement and maintain full installation instructions, but it might be good to specify it as a requirement and add a few links to Boost.

**Comment by patricksjackson** [comment]
Yes, the idea was to give students pointers to Boost and not maintain Boost install instructions ourselves. These are both side exercises that can be skipped if necessary, and it really is infeasible for us to maintain instructions.

#318 is the right approach to me.
