### ISSUE TITLE
Update README.md files to C++14

### ISSUE THREAD

**Issue by siebenschlaefer** [exercism/cpp#312]
All `README.md` files contain a paragraph that starts with "Try to use standard C++11 facilities".  
Since we upgraded the minimum requirements to C++14 we should also update those paragraphs.

**Comment by KevinWMatthews** [comment]
@siebenschlaefer - very true. Thanks!

**Comment by KevinWMatthews** [comment]
@siebenschlaefer Should be fixed. If you see something else, feel free to reopen the issue.

**Comment by siebenschlaefer** [comment]
Looks good. Thanks!
