### ISSUE TITLE
binary-search should be solved using first principles

### ISSUE THREAD

**Issue by siebenschlaefer** [exercism/cpp#313]
The file `README.md` of all exercises contains a paragraph that says "*Try to use standard C++11 facilities in preference to writing your own low-level algorithms or facilities by hand.*"

AFAIK there are only three exercises that should not be solved by using a function from the standard library:
- binary: "*Convert a binary number [...] using first principles. [...] Implement the conversion yourself. Do not use something else to perform the conversion for you.*"
- hexadecimal: "*Convert a hexadecimal number [...] using first principles (i.e. no, you may not use built-in or external libraries to accomplish the conversion).*"
- all-your-base: "*Try to implement the conversion yourself. Do not use something else to perform the conversion for you.*"

"binary-search" should do the same. The exercise can be solved in a few lines by using `std::lower_bound()` or `std::upper_bound()` but the way its `README.md` describes the underlying algorithm probably means that the author wanted a manual implementation.

That was also the consensus on Slack, see [thread 1](https://exercism-team.slack.com/archives/CASG1FXUJ/p1568953364002300) and [thread 2](https://exercism-team.slack.com/archives/CAQP7JL3T/p1569005155049200).

**Comment by KevinWMatthews** [comment]
@siebenschlaefer also true.

Is the same true of the binary search exercise?

Thanks for the links, but I actually need to figure out how to join Slack. For now I'll take your word for it.

**Comment by siebenschlaefer** [comment]
> Is the same true of the binary search exercise?

Sorry if was being unclear.

Currently: The instructions of binary, hexadecimal, and all-your-base tell students to do the algorithm by hand. The instructions of binary-search do not.

Proposal: The instructions of binary-search should also tell students to do the algorithm by hand.

**Comment by KevinWMatthews** [comment]
Agreed. I'll open a PR shortly.

**Comment by KevinWMatthews** [comment]
@siebenschlaefer Should be fixed. If you see something else, feel free to reopen the issue.
