### ISSUE TITLE
Secret handshake locked when it shouldn't be

### ISSUE THREAD

**Issue by mikewalker** [exercism/cpp#320]
I have completed all of core and 22 of the side exercises. I believe that reverse string should have unlocked secret handshake, but it remains locked.

**Comment by KevinWMatthews** [comment]
Hi @mikewalker , thanks for letting us know.
Did you complete reverse string before secret handshake was created or after?

**Comment by mikewalker** [comment]
Update: I'm not sure how to explain this. Maybe something changed overnight on the site but it is now unlocked. Maybe some nightly maintenance script caught the problem?

**Comment by patricksjackson** [comment]
This is an issue we've hit before, it happens because this exercise was added recently, and an update script needs to be run by @iHiD to make it active on the track. (It will show up as locked for everyone on the site until then).

@iHiD Either started running the script regularly or just happened to run it between the two times that you checked :)

**Comment by NobbZ** [comment]
The script is not run on a nightly base… The last time I talked with @iHiD about it, he said it takes 6 hours to run, and I have to assume that this script doesn't get faster as tracks, exercises and users grow in numbers…

So I'd guess its more on a weekly to monthly schedule, or a simple "whenever I see an issue popping up" :D

**Comment by mikewalker** [comment]
I understand, thanks for the explanation. It would be nice if new exercises where hidden on the site until the script is run. Then again that might be more work than its worth. :)

**Comment by iHiD** [comment]
Hello :) It's whenever someone asks me to run it. I ask maintainers to tell me when the config.json is changed with anything that effects unlocking and then I run it. Someone did today so it's probably caught it :)

**Comment by KevinWMatthews** [comment]
Ah, I didn't ping iHid to run the script. Will do next time!
