### ISSUE TITLE
Unit tests for space_age exercise do not drive to a correct implementation

### ISSUE THREAD

**Issue by tronthomas** [exercism/cpp#327]
I was working on the space_age exercise, and the tests written for it appear to be insufficient and do not seem to drive someone toward creating a correct implementation.

Following the TDD principle of doing the simplest thing to make a test pass, for most tests, someone can simply hard code the expected values for almost everything except the on_earth method, and  then all the tests will pass.

For example, someone can implement the seconds method like this:

```
    int space_age::seconds() const {
        return 1000000;
    }
```
to make the first test pass. Nothing else in the test suite will require someone to change that implementation. Similar things are true for on_mercury, on_venus, etc.

**Comment by siebenschlaefer** [comment]
The C++ track tries to stick closely to the [original problem specification](https://github.com/exercism/problem-specifications/blob/master/exercises/space-age/canonical-data.json).

I'd suggest that you open an issue there, and once those tests are changed the C++ track will (eventually) mimic those changes.

**Comment by patricksjackson** [comment]
As @siebenschlaefer said, this one is better handled by the problem-specifications repo. (This distinction isn't really clear from our README, so any confusion is our fault, sorry about that).

I see you've already opened an issue there in https://github.com/exercism/problem-specifications/issues/1626, so I'll go ahead and close this. Thanks!
