### ISSUE TITLE
Inconsistency in exercise topics

### ISSUE THREAD

**Issue by heitorPB** [exercism/cpp#329]
There are interesting topic names here: `algorithms` and  `algorithm`.
There's also `Control Flow If Else Statements` and `Control Flow Conditionals`.
And also `Control Flow loops` and `Loops`.

 In [problem-specifications/TOPICS.txt](https://github.com/exercism/problem-specifications/blob/master/TOPICS.txt) there are `algorithms`, `loops`, `conditionals`. 

Is there a reason for this? I'd like to submit a PR to fix it, if it was not intentional.

**Comment by KevinWMatthews** [comment]
Hi @heitorPB , sorry we missed this!

It probably isn't intentional. I'm guessing that the problem specifications repo has evolved over time and that we didn't notice the change. A PR is welcome.
