### ISSUE TITLE
Recruiting additional maintainers for C++

### ISSUE THREAD

**Issue by kytrinyx** [exercism/cpp#332]
We're about to start a big push towards version 3 (v3) of Exercism. This is going to be a really exciting step forward for Exercism, with in-browser coding, new Concept Exercises with automated feedback, improved mentoring and much more.

This to be a big community effort, with the work spread out among hundreds of volunteers across Exercism. One key thing is going to be each track having enough maintainers who have the time to manage that community effort. We are therefore putting out a call for new maintainers to bolster our numbers. We're hoping that our existing maintainers will be able to act as mentors to the newer maintainers we add, and take on a parental role in the tracks.

If you are an existing maintainer, could you please reply to this letting us know that you think you'll have time (2-3hrs/week) to help with this over the next 6 months. If you won't have that time, but still want to be a maintainer and just help where you can instead, please tell us that too. If you have come to the end of the road as a maintainer, then we totally understand that and appreciate all your effort, so just let us know.

For anyone new who's interested in becoming a maintainer, thanks for your interest! Being an Exercism maintainer is also a great opportunity to work with some other smart people, learn more about your language of choice, and gain useful skills and experience that are useful for growing your career in the technical leadership direction. Please write a comment below introducing yourself along with your Exercism handle, and telling us why you're interested in becoming a maintainer, and any relevant experience. We will then evaluate every application and contact you using your exercism email address once we have finished the evaluation process.

Thank you!

See also https://github.com/exercism/exercism/issues/5161

**Comment by AtnNn** [comment]
Please count me in! I've recently started mentoring on exercism. I'm a senior C++ developer at @Nitro.

**Comment by siebenschlaefer** [comment]
Slightly off-topic: We could use mentors, too. If the numbers in the "Weekly Mentoring Update" are correct there were only 15 out of 210 review in the last four weeks that weren't done by me. I'm not complaining, reviews are a fun thing to do. But should I drop out or find significantly less time the queue would clog up quickly.

**Comment by sebito91** [comment]
Would be happy to help out both with mentoring and maintenance of the track! Would be able to dedicate about ~1-2 hrs/wk for this track.

**Comment by patricksjackson** [comment]
@siebenschlaefer I had no idea the mentoring situation was that bad... Mentoring definitely needs some more people to help out actively.

Even before the exercism v3 stuff was announced, I was planning to make a post like this to ask for more help.

I've been maintaining the track for several years now, and @KevinWMatthews has been working with me as well for the past year or so. The track though has been very much in 'maintenance mode', as we just have not had very much time to dedicate to it. The only thing I've spent significant time on was doing the Boost->Catch migration, and otherwise I easily spend <2 hours a week, usually <1.

I don't plan to leave, but I also don't expect that I will have much additional time to spend on moving the track to v3.

**Comment by lmarcell** [comment]
I also have some interest too help, however it is still not very clear what it's all about.

**Comment by iHiD** [comment]
@l0nax @lmarcell Thanks :) @ErikSchierboom will follow up. In the interim there is more info here https://github.com/exercism/v3

**Comment by giorgiozoppi** [comment]
Count on me.

**Comment by iHiD** [comment]
@lmarcell What's your exercism handle?

**Comment by lmarcell** [comment]
@iHiD I had some cpp mentoring activity some time ago

**Comment by iHiD** [comment]
Cool. I still need to know your handle (username) though :)

**Comment by lmarcell** [comment]
Ah, sry for the missunderstanding. It's RelaxedProgrammer

**Comment by kpraveenkumar** [comment]
I am interested in contributing to exercism V3 and happy to be the part of this contribution.

**Comment by Vaibhavi24** [comment]
I've >6 yrs of experience in C++. Picked the ropes of programming in High School and have been a passionate programmer ever since. Feeling really excited to contribute to the learning process of so many on exercism :)

**Comment by SourangshuGhosh** [comment]
I'm highly interested to be a maintainer in this community. I have done many projects especially in C++ language. @iHiD can you please add me as a maintainer so that I can contribute to the maximum.

**Comment by ErikSchierboom** [comment]
@SourangshuGhosh I've sent you an email with the details on how to become a maintainer. Thanks so much for wanting to help!

**Comment by ErikSchierboom** [comment]
We're closing this issue as it was part of our push to implement the v3 version of this track and v3 has [just been released](https://exercism.org/blog/exercism-v3-has-launched).

New maintainer are always welcome though!
