### ISSUE TITLE
Hello World missing tests or just confused

### ISSUE THREAD

**Issue by ehenderichs** [exercism/cpp#334]
Complete newby to exercism and after reading documentation and setting up VS 2020 I downloaded the Hello World exercise via the cli. The downloaded folder does not contain any unit tests. Was under the impression all exercises would already contain unit tests. 

Comparing the files downloaded with the hello world files in the repo, I am missing:
- hello_world_test.cpp
- example.cpp

Did something go wrong downloading or should I also create my own unit tests?

**Comment by KevinWMatthews** [comment]
Hi @ehenderichs ,

Welcome to exercism! I'm sorry that things didn't work out of the box.

You're right; the idea is that exercism provides the tests and students provide the solution. If you don't see a test suite (`hello_world_test.cpp`), something has indeed gone awry.

A few ideas for troubleshooting: do you see a button that says "Update exercise to latest version?". If you're completely new to exercism then I can't imagine that you would, but if you do, please click it and then try the download again.

On my Linux machine, I'm able to download the exercise successfully using:

```
$ exercism download --exercise=hello-world --track=cpp
```

Then I see these files:

```
~/coding/exercism/cpp $ tree hello-world
hello-world
├── CMakeLists.txt
├── hello_world.cpp
├── hello_world.h
├── hello_world_test.cpp
├── README.md
└── test
    ├── catch.hpp
    └── tests-main.cpp
```

Note that I have customized my download location:

```
$ cat ~/.exercism.json
    # ...
    "dir": "/home/kevin/coding/exercism",
    # ...
```

Can you send us similar information? Specifically,

  * The command used to download
  * The download location
  * The complete list of downloaded files

Note that one file is missing: `example.cpp`. This is a completed solution that is primarily used by track maintainers (to validate the test suite) or by mentors (for reference). We don't send it to students before they start working - that would defeat the purpose of the exercise.

Hope that helps! If nothing else, it will give us a starting point.

**Comment by ehenderichs** [comment]
Hi Kevin,

Thanks for your response. You don't have to be sorry about anything. It is me who should be sorry.

The download did work correctly, I was looking in the wrong location. When setting up, I was playing around with the CMake project (new for me) and called my test project hello_world (not the best choice in hindsight). After download I simply opened the wrong folder, not registered the location was mentioned after download. From that point on just stared blind a problem that was not there. 

Sorry inconvenience, will look more carefull next time before opening a ticket.

**Comment by KevinWMatthews** [comment]
Hi @ehenderichs ,

Not to worry! Glad that you're up and running.

I'll close this, but feel free to get in touch if something else goes wrong.
