### ISSUE TITLE
Exercise still in queue

### ISSUE THREAD

**Issue by stefansilverio** [exercism/cpp#349]
The exercise below on the C++ track has been waiting in the queue for mentor review for about four days. It says "There are currently 0 solutions ahead of this in the C++ queue, and 0 ahead in the Reverse String queue. The median waiting time for mentoring on this exercise is about 2 hours." I had a mentor change so I just want to make sure nothings wrong and that this gets picked up. Thanks.
https://exercism.io/my/solutions/0e39cbce3a8343d091e39967ae108540

**Comment by bobrundle** [comment]
This issue can be closed.  I picked the exercise.

**Comment by siebenschlaefer** [comment]
Thanks
