### ISSUE TITLE
CMake Error - nucleotide_count

### ISSUE THREAD

**Issue by milliorn** [exercism/cpp#350]
I am getting this error when I download this exercise.  I use Visual Studios Community.  I use catch2 in VS and VSC without issue, and so I'm not sure why I am getting this error or how to resolve it?

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		CMake Error at C:\Users\scott\Documents\Coding\Tutorials\Exercism\C++\Side\nucleotide-count\CMakeLists.txt:26 (add_executable):
  Cannot find source file:

    test/tests-main.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx		C:\Users\scott\Documents\Coding\Tutorials\Exercism\C++\Side\nucleotide-count\CMakeLists.txt	26	
```

**Comment by siebenschlaefer** [comment]
There should be a directory `C:\Users\scott\Documents\Coding\Tutorials\Exercism\C++\Side\nucleotide-count\test` the two files: `catch.hpp` and `tests-main.cpp`. Can you see them?

**Comment by milliorn** [comment]
I am missing **tests-main.cpp**.
![image](https://user-images.githubusercontent.com/39207179/81991969-50022500-95f7-11ea-9e7e-dcee1c34c355.png)

**Comment by siebenschlaefer** [comment]
Short term fix: Download [tests-main.cpp](https://github.com/exercism/cpp/blob/master/exercises/nucleotide-count/test/tests-main.cpp) and put it in the `test` directory.

But before you do that, can you try downloading the exercise a second time?
```bash
exercism download --exercise=nucleotide-count --track=cpp
```
Does that download the missing file?

**Comment by milliorn** [comment]
![image](https://user-images.githubusercontent.com/39207179/81992451-4fb65980-95f8-11ea-89bb-6de6b74396f3.png)
![image](https://user-images.githubusercontent.com/39207179/81992468-5a70ee80-95f8-11ea-8789-2281d3eb6f9a.png)
Not sure what happened.  My guess is that the IDE deleted the file?  I will open it in Visual Studios.
![image](https://user-images.githubusercontent.com/39207179/81992626-c2bfd000-95f8-11ea-8bd1-c9a5dfb709d5.png)
Not sure what happened.  Maybe Visual Studio Code did something to it?
![image](https://user-images.githubusercontent.com/39207179/81992713-01558a80-95f9-11ea-909d-ed9390d3d826.png)
So I have no clue what happened?  Guess I will close this issue.  Thank you!?

**Comment by siebenschlaefer** [comment]
Strange.  
At least it's fixed for now.

Have fun with the exercise!
