### ISSUE TITLE
New test case need for Triangle to test for templates with single type.

### ISSUE THREAD

**Issue by bobrundle** [exercism/cpp#351]
Some students are solving the triangle exercise with templates...not the simplest path but not wrong either.  The problem is that the common template solution involves a declaration like this...
```

    template <typename T>
    flavor kind(T a, T b, T c)


```
This will pass all unit tests, however will fail this unit test...

```
TEST_CASE("mixed_types_are_legal")
{
    REQUIRE(triangle::flavor::isosceles == triangle::kind(10.0, 10.0f, 2));
}


```
So a unit test to check for mixed argument types to the kind function needs to be added.

**Comment by siebenschlaefer** [comment]
There's a [pull request](https://github.com/exercism/cpp/pull/347) by @elyashiv that tries to fix this:

**Comment by AlexLeSang** [comment]
> [PR-347](https://github.com/exercism/cpp/pull/347) by @elyashiv tries to fix this.

The PR has been merged. New test case added.
