### ISSUE TITLE
How to run the file to work on problem, and which file?

### ISSUE THREAD

**Issue by Al-Campuzano** [exercism/cpp#359]
I am totally new to C++ so pardon my ignorance. The instructions here are not clear: https://exercism.io/tracks/cpp/tests

I'm using Atom to open/edit the exercise files, it is my understanding that the changes I need to make would be in the `hello_world.cpp` file for this first problem, but how do I run it? 

I can run other cpp files from Atom using the [gpp-compiler package](https://atom.io/packages/gpp-compiler), but that doesn't work for the `hello_world.cpp` file and I get the following error:

```
Undefined symbols for architecture x86_64:
"_main", referenced from:
implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Also is that the correct file that i'm supposed to be working on and submitting? again the instructions are very vague regarding this. It seems they make some big assumptions about the level of familiarity with C++ that people have coming into this.

Anyway, I appreciate your help!

**Comment by siebenschlaefer** [comment]
Until an experienced Atom user can help you, you could use the command line. Open the terminal, go to the directory of the exercise and type `cmake .` and then `make`

**Comment by Al-Campuzano** [comment]
Thank you for that. It would be helpful to have that information in the docs. I did not find anything that explains how to run the program ¯\_(ツ)_/¯

**Comment by siebenschlaefer** [comment]
When you run `make`, your solution and the tests will be compiled, linked and then the tests will be executed automatically.  
It should looks similar to this:
```
[ 25%] Building CXX object CMakeFiles/hello-world.dir/hello_world_test.cpp.o
[ 50%] Building CXX object CMakeFiles/hello-world.dir/hello_world.cpp.o
[ 75%] Building CXX object CMakeFiles/hello-world.dir/test/tests-main.cpp.o
[100%] Linking CXX executable hello-world
[100%] Built target hello-world
===============================================================================
All tests passed (1 assertion in 1 test case)

[100%] Built target test_hello-world
```

**Comment by Al-Campuzano** [comment]
OH maybe it is there in the doc about tests, but i totally missed it. It's not very clear to me that `make` _runs_ the program. 

Thank you, @siebenschlaefer
