### ISSUE TITLE
How to set up debugger in visual studio code for programs in the C++ track?

### ISSUE THREAD

**Issue by jerabaul29** [exercism/cpp#360]
On the Cpp track, how would you recommend to set up the debugger for example for a visual studio code user? I ask since with the test suite, it is not clear to me how to get the debugger running.

**Comment by AlexLeSang** [comment]
Hi! Have you taken a look at https://code.visualstudio.com/docs/cpp/cpp-debug? 

Are you still facing this issue?

**Comment by patricksjackson** [comment]
Setting up a debugger depends on your environment, this is an old issue, but for anyone seeing this I'd suggest looking up how to use a debugger in general for your IDE/setup.

The test suite uses Catch for testing,  and has a fairly standard CMake build file. Those are some of the most common build tools used for C++ code in general, so you shoul dhave no problem finding instructions on handling them.

The only slightly odd setup thing her is that the CMake file automatically runs the test file on a build, but that probably doesn't cause problems for debugging.
