### ISSUE TITLE
Introduction missing for Protein Translation exercise

### ISSUE THREAD

**Issue by mikewalker** [exercism/cpp#361]
The Introduction for the  Protein Translation exercise is shown as the single word "Introduction" with no text below that.

**Comment by patricksjackson** [comment]
Are you seeing that on the website? I just checked and I could see the full description, it should be the text in the README here - https://github.com/exercism/cpp/tree/master/exercises/protein-translation

There doesn't seem to be an issues here, but it might be an issue with the Website if you're still seeing it. In which case we'd need to open an issue in https://github.com/exercism/exercism

**Comment by mikewalker** [comment]
Yes it does appear to be just the website.
