### ISSUE TITLE
Improve Concept Exercise: strings

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/cpp#416]
Taking a look at the [strings exercise](https://github.com/exercism/v3/blob/master/languages/cpp/exercises/concept/strings), I've found some things that can be improved:

- The [stub file](https://github.com/exercism/v3/blob/master/languages/cpp/exercises/concept/strings/strings.cpp) does not contain stubs for the methods the student needs to implement. These should be added (see [the docs](https://github.com/exercism/v3/blob/master/docs/concept-exercises.md#stub-implementation-file)).
- The example implementation file uses the `const` modifier. As per [the docs](https://github.com/exercism/v3/blob/master/docs/concept-exercises.md#example-implementation-file), the example implementation should only use language features introduced by the exercise or its prerequisites (and their prerequisites, and so on). Is `const` introduced in one of the prerequisites?

**Comment by vaeng** [comment]
This has been addressed and updated.
