### ISSUE TITLE
Catch2 v2.7.0 breaks on Apple Silicon

### ISSUE THREAD

**Issue by pr1metine** [exercism/cpp#432]
Hello exercism,
I am an utter beginner in C++ which is why I decided to go through that CPP track. Shortly after starting it, I got stuck at `hello-world`.

# Problem
All practices for the cpp track run fine so far on my PC. However, that is not the case for my M1 MacBook Air when using Apple Clang and CLion. Instead, it throws errors as shown in the log below: 

```log
====================[ Build | hello-world | Debug ]=============================
"/Users/pr1metine/Library/Application Support/JetBrains/Toolbox/apps/CLion-ARM/ch-0/203.7148.70/CLion.app/Contents/bin/cmake/mac/bin/cmake" --build /Users/pr1metine/projects/Exercism/cpp/hello-world --target hello-world -- -j 6
[ 25%] Building CXX object CMakeFiles/hello-world.dir/test/tests-main.cpp.o
In file included from /Users/pr1metine/projects/Exercism/cpp/hello-world/test/tests-main.cpp:2:
/Users/pr1metine/projects/Exercism/cpp/hello-world/test/catch.hpp:6317:13: error: invalid token in expression
            CATCH_BREAK_INTO_DEBUGGER();
            ^
/Users/pr1metine/projects/Exercism/cpp/hello-world/test/catch.hpp:6035:79: note: expanded from macro 'CATCH_BREAK_INTO_DEBUGGER'
    #define CATCH_BREAK_INTO_DEBUGGER() []{ if( Catch::isDebuggerActive() ) { CATCH_TRAP(); } }()
                                                                              ^
/Users/pr1metine/projects/Exercism/cpp/hello-world/test/catch.hpp:6014:34: note: expanded from macro 'CATCH_TRAP'
    #define CATCH_TRAP() __asm__("int $3\n" : : ) /* NOLINT */
                                 ^
<inline asm>:1:6: note: instantiated into assembly here
        int $3
            ^
In file included from /Users/pr1metine/projects/Exercism/cpp/hello-world/test/tests-main.cpp:2:
/Users/pr1metine/projects/Exercism/cpp/hello-world/test/catch.hpp:6317:13: error: invalid operand
            CATCH_BREAK_INTO_DEBUGGER();
            ^
/Users/pr1metine/projects/Exercism/cpp/hello-world/test/catch.hpp:6035:79: note: expanded from macro 'CATCH_BREAK_INTO_DEBUGGER'
    #define CATCH_BREAK_INTO_DEBUGGER() []{ if( Catch::isDebuggerActive() ) { CATCH_TRAP(); } }()
                                                                              ^
/Users/pr1metine/projects/Exercism/cpp/hello-world/test/catch.hpp:6014:34: note: expanded from macro 'CATCH_TRAP'
    #define CATCH_TRAP() __asm__("int $3\n" : : ) /* NOLINT */
                                 ^
<inline asm>:1:6: note: instantiated into assembly here
        int $3
            ^
2 errors generated.
make[3]: *** [CMakeFiles/hello-world.dir/test/tests-main.cpp.o] Error 1
make[2]: *** [CMakeFiles/hello-world.dir/all] Error 2
make[1]: *** [CMakeFiles/hello-world.dir/rule] Error 2
make: *** [hello-world] Error 2
```

# Fix
Luckily, I was able to fix this issue by bumping `Catch2` to the latest version (i. e. overwrite `test/catch.hpp` with [Catch2 v2.13.4](https://github.com/catchorg/Catch2/releases/download/v2.13.4/catch.hpp)). Thus, bumping all occurrences of `catch.hpp` will likely resolve this.

**Comment by siebenschlaefer** [comment]
I can't reproduce the issue because I don't have a Mac but upgrading to the latest version of Catch2 sounds like a good fix and probably won't cause any issues. +1 from me.

@pr1metine I'm not sure how long it takes to fix it. In the meantime you could overwrite `catch.hpp` manually with the latest version.

**Comment by pr1metine** [comment]
> @pr1metine I'm not sure how long it takes to fix it. In the meantime you could overwrite catch.hpp manually with the latest version.

Yeah, this will have to do for now. 

If it helps, I found the reason for the aforementioned errors. 

https://github.com/exercism/cpp/blob/5001cfba7a48baae7aa8d4c92b3a028630c84433/test/catch.hpp#L6012-L6015 

Previously, Catch assumed that MacOS ran on Intel (hence the `x86_64 assembly` code inside the brackets). But ARM Macs cannot properly interpret `x86_64` code. Therefore in [newer versions](https://github.com/pr1metine/cpp/blob/52cda99b41854b84409c31910afceb11587c32b4/test/catch.hpp#L7931-L7937), they now provide `ARM` code specifically for Apple Silicon.

Curiously enough, I managed to run the CPP exercises on my Raspberry Pi (with some difficulties with regards to CLion Remote Development).

**Comment by damianofranzo** [comment]
I have an M1 MacBook, and I have the same issue. I solved by applying the same changes as the commit you find above from another repository.

https://github.com/r-lib/testthat/pull/1246/commits/069ffffd4c2ed3323d755a6226055dea6dbd06e7

Do you think it could be applied to this repository as well?

**Comment by pr1metine** [comment]
Yeah. Among other things, I already provided that fix 2 months ago. It's up to the maintainers to finally incorporate these changes into the codebase.
