### ISSUE TITLE
Rename `strings` Concept Exercise to use story/theme

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/cpp#470]
In the beginning of v3 development, Concept Exercises were named after their Concepts. However, we've later on changed this to have the Concept Exercises be named after their story/theme.

The `strings` Concept Exercise should be updated to use a story/theme-based name and slug.

See https://github.com/exercism/v3-launch/issues/49

**Comment by patricksjackson** [comment]
The only concept exercise here is `strings` which only consisted of a stub. It's being removed in #485

**Comment by krish40786** [comment]
Hi, I can take a look at this. I had a quick question, do I need to come up with a name or should I use one of three mentioned in 
https://github.com/exercism/v3-launch/issues/49 ?

**Comment by ErikSchierboom** [comment]
@krish40786 Great! Looking at [its metadata](https://github.com/exercism/cpp/blob/main/exercises/concept/strings/.meta/config.json#L7), it is forked from the `csharp` track's `log-levels` exercise. I would thus rename it to `log-levels`.

**Comment by krish40786** [comment]
created a pull request https://github.com/exercism/cpp/pull/534 for this. Let me know if it looks all right.

**Comment by vaeng** [comment]
This has been solved and updated. Thanks @krish40786
