### ISSUE TITLE
Luhn "a simple valid SIN that becomes invalid if reversed" is wrong or unclear

### ISSUE THREAD

**Issue by ViralTaco** [exercism/cpp#473]
https://github.com/exercism/cpp/blob/7e75421ab1c195981401ea6a5666315d90a7b5dc/exercises/practice/luhn/luhn_test.cpp#L38-L45

```
59
5 + (2 * 9 - 9) = 5 + 9 = 14
```
14 is not evenly divisible by 10. 
Either the test meant to test for
```
95
9 + (5*2 - 9) = 9 + 1 = 10
```
Or it's unclear what this test tests for. 

EDIT: The answer is 3, the exercice description isn't clear

**Comment by siebenschlaefer** [comment]
You might have missed a crucial piece of information in the instructions:
"The first step of the Luhn algorithm is to double every second digit, **starting from the right.**"

**Comment by ViralTaco** [comment]
> You might have missed a crucial piece of information in the instructions:
> "The first step of the Luhn algorithm is to double every second digit, **starting from the right.**"

Yes, the example in the markdown file is unclear, in my opinion. 
Also: how are you doing?
