### ISSUE TITLE
C++ track Hamming does not work properly

### ISSUE THREAD

**Issue by ahdach** [exercism/cpp#474]
Hi,

To exercise I do the following:
1. Download using the provided bash command
2. Navigate to the exercise folder
3. Create build folder
4. From within the build folder run 'cmake -G Xcode ..'
5. Open the project in xCode
  - Open...
  - Select the .xCodeProj file in the build folder

A this stage I built (for the Hello World) or fix compiling errors (for Nucleotide Count).
Strangely, the Hamming exercise does not show compiling errors. Although the hamming::compute method is not defined. As if the test file is not considered.
Any idea?

**Comment by patricksjackson** [comment]
Hamming should have an identical initial setup to every other exercise. Is
this blocking you from actually doing the exercise?

I don't have a Mac and so I can't test that flow directly, but we do test
on Macs so it should be working fine.

**Comment by ahdach** [comment]
HI Patrick,

Thanks for your reply.

Well. The project builds successfully but does not produce the executable.
So, I guess I could do the exercise blindly but would miss the TDD process.

I'll pass that one, provide the solution I find. Thought its worth letting other people know.
As it helped me finding out in the github issues relating to the Hello World exercism...

Kind Regards
