### ISSUE TITLE
'Hello World' exercise is missing header file when downloaded via the CLI

### ISSUE THREAD

**Issue by dylanwright** [exercism/cpp#482]
When downloading via the CLI, the project is missing hello_world.h but CMakeLists.txt is still looking for it.

ref: https://github.com/exercism/cpp/blob/26352eb5dccf8553228add904ae6aca227e3b07f/exercises/practice/hello-world/CMakeLists.txt#L35

I think it could be due to changes to config.json in commit [7e75421](https://github.com/exercism/cpp/commit/7e75421ab1c195981401ea6a5666315d90a7b5dc#diff-5ab184438a2f2595277344b75c576e1471c27226ad6e0f030df90c0380526f01)

Completing the challenge via the online editor required a 1 one line change, but via the CLI I had to create a header file in order to build and run the tests.

**Comment by patricksjackson** [comment]
I think you're completely correct, I've opened a PR to fix it. Looks like it was just a misunderstanding when that change was made.

Thanks for reporting. In the future you're welcome to setup the PR yourself as well :)
