### ISSUE TITLE
'Gigasecond' exercise works in Visual Studio but when submitted via CLI shows as Failed

### ISSUE THREAD

**Issue by krnets** [exercism/cpp#483]
The message on website when checking Tests status is:

AN ERROR OCCURRED
"We received the following error when we ran your code:
make: *** No targets specified and no makefile found.  Stop."

**Comment by patricksjackson** [comment]
Thanks! There's investigation ongoing in https://github.com/exercism/exercism/issues/5729

**Comment by patricksjackson** [comment]
Closing this, for updates follow the above linked issue.
