### ISSUE TITLE
C++ track description mentions more paradigms than C++ track flags

### ISSUE THREAD

**Issue by Pablo-No** [exercism/cpp#489]
I don't know if that's intended.
https://github.com/exercism/cpp/blob/26352eb5dccf8553228add904ae6aca227e3b07f/config.json#L11
https://github.com/exercism/cpp/blob/26352eb5dccf8553228add904ae6aca227e3b07f/config.json#L739

**Comment by vaeng** [comment]
To quote iHiD: 
> most languages support most paradigms, so we try to just choose the main ones that are used day-to-day in any given language.
So it is intended.
