### ISSUE TITLE
Typo in instructions.md for `say` exercise - instruction examples incorrectly include string `and`

### ISSUE THREAD

**Issue by ntmartinez** [exercism/cpp#507]
The test cases in the `say` exercise do not include the string literal `"and"` for test cases like `123 -> "one hundred twenty-three"`, but the instructions *do* include `"and"` in their example cases; for example, the instructions say `120` becomes `"one hundred and twenty"`, but the test cases in the code do not include the `"and"` string.

This is a typo in the example cases in the instructions; the example cases in the instructions need to be fixed to have the `and` removed from all of them so that they match the test cases (no more ambiguity).

PR https://github.com/exercism/cpp/pull/506 fixes this.

I'm a first time contributor; please let me know if I missed anything. I'm not sure if this typo exists in the instructions for this problem in other programming languages too (if this problem even exists in other languages). Thanks :slightly_smiling_face:

**Comment by patricksjackson** [comment]
Unfortunately fixing the instructions is going to be more work than changing the code to match the instructions. What we should do instead is change the tests (and example solution) to match the instructions.

Also, nice job on following up on this. This discrepancy has existed for at least 5 years and nobody has noticed it so far :)

For the majority of exercises (I think all of them in the C++ track) they use a common set of instructions from https://github.com/exercism/problem-specifications. The instructions that are checked into this repo is just a copy of https://github.com/exercism/problem-specifications/blob/main/exercises/say/description.md

There's a description of the process that's used here: https://github.com/exercism/docs/blob/main/building/tracks/practice-exercises.md#file-docsinstructionsmd

**Comment by ntmartinez** [comment]
Hi @patricksjackson - sorry, was busy with life.

Ah, I didn't realize that. Right - if exercism/cpp just copies description.md from exercism/problem-specifications (as presumably other exercism-supported languages do too), then other languages' implementations may actually be correct (perhaps - haven't gone and looked yet), and the assumption now is just that the cpp implementation is wrong.

Well, if you want me to change the implementation (test cases, etc), I can do that. My only reservation is that all of peoples' existing solutions for this problem will be invalidated once the test cases changes. But maybe that's not actually that big of a deal.

Are you an approver for the cpp repo? If so, and you decide that you do want me to go ahead and change the cpp implementation for this problem, I can do that this weekend.

Thanks! Sorry for the delay in response.

**Comment by ntmartinez** [comment]
And apparently this is the reason why all languages have the same (faulty) test cases - https://github.com/exercism/problem-specifications/blob/main/exercises/say/canonical-data.json. If my understanding is correct, all languages generate code to implement these test cases. That's what's stated here: https://github.com/exercism/problem-specifications#test-data-canonical-datajson

I'm thinking the right thing to do at this point is close this issue & the PR I created and open a PR on exercism/problem-specifications to change the docs to exclude `"and"` from the examples. That would seem to bring correctness to every language (hopefully).

If you think there's anything I'm not considering, please let me know. Thank you!

**Comment by patricksjackson** [comment]
Oh, I see what's going on, we've both been misreading the instructions. Sorry I missed clearing this up earlier.

The instructions that tell you to use `and` are part of a section titled `Extensions`. It's not explained well in this exercises instructions, but that is a suggestion for extra tests or future _extensions_ of the exercise that the student (or a track) could do on their own. Some of the tracks call it "extra credit" or something similar.

Notice that all of the examples before the `Extensions` section do not use `and` - https://github.com/exercism/problem-specifications/blob/main/exercises/say/description.md

So yea, the docs in the problem description should maybe be clearer about that section being an extension, but everything else is correct.

Again, sorry I didn't notice this the last time, but thanks for being so diligent looking into the issue :)
