### ISSUE TITLE
Reuse names in "robot-name" exercise

### ISSUE THREAD

**Issue by AlexeyMarkarov** [exercism/cpp#545]
Please improve either the wording of "robot-name" instructions or its tests to explicitly permit or deny the reuse of names.

Currently, robots have the ability to get their names wiped, and at the same time instructions require names to be random. It means that if a robot had a name, then got it wiped, then got another name - the new name is equally likely to be its old name as any other possible name. Otherwise names would not be truly random if they had a constraint that a given robot should not repeat its names.
Also, if the number of robots is >= the number of possible name combinations then the only name a robot can get after wipe is its old name.

This makes test cases *"is_able_to_reset_name"* and *"exhausting_digits_yields_different_names"* somewhat depend on luck.
I had one of the tests fail (using the editor), and then I simply rerun it and it passed.

**Comment by siebenschlaefer** [comment]
I agree, the instructions could be improved. But that should probably be done in the language-agnostic [problem-specifications](https://github.com/exercism/problem-specifications) repository. IIRC the three most common discussions are about:

- Should the destructor make old names available again or are those names "burned" forever?
- Similarly, when a robot gets reset is the old name "burned" forever or will it become available again at some, e.g. when the instance gets destructed?
- Is it acceptable to repeatedly generate new random names until an unused one is found (even if that might take some time when there are many names already used) or should the tests encourage/enforce some other approach that guarantees better worst-case response times?
- Is it acceptable to assign a name at construction / during the reset, or should the instructions be followed closely and the name be generated upon request?
- What should happen if there are no more unused names left?

As for the tests I'd argue that they are not "acceptance tests" where every solution that passed them is automatically correct but rather in the style of test-driven development where the tests *guide* the programmer and it's still up to the programmer to read the instructions and tests carefully and write a reasonable solution, not just a "hack" that happens to pass the tests.  
In this case the test ["exhausting_digits_yields_different_names"](https://github.com/exercism/cpp/blob/main/exercises/practice/robot-name/robot_name_test.cpp#L60-L72) clarifies the requirements: A `reset()` should not yield any of the old names of the robot.  

Also, everything involving randomness is hard to test. I wouldn't know how to reliably test something like "The names must be random: they should not follow a predictable sequence." And I've seen (incorrect) solutions that consume and discard one or two random numbers just to pass the tests, or let each instance maintain its own set of used names where collisions between different instances are just avoided by chance.  
That' why mentoring is such a great feature: Often mentors know these aspects and have seen multiple different solutions, they can point out any hidden issues and discuss the interpretation of the task.

There have been discussions about this exercise in the past (e.g. https://github.com/exercism/problem-specifications/issues/1673 or https://github.com/exercism/problem-specifications/issues/1831).
