### ISSUE TITLE
Exercise for a "Code Organization" concept

### ISSUE THREAD

**Issue by vaeng** [exercism/cpp#596]
I would like to have an exercise that enables the user to handle imports and distribute the codebase over several files.

I think the following topics should be covered:

- Header and source files
- Includes and include guards
- Namespaces

The related concept will cover how and why. The exercise has to be written from scratch as there is no similar concept yet as far as I know. This is the main reason I want to split the two tasks.

---

- [ ] Conceptualize a fitting exercise
- [ ] Add code files
- [ ] Add documentation files
- [ ] Update the list of implemented exercises
- [ ] Get feedback
- [ ] Implement Feedback

**Comment by vaeng** [comment]
My first idea for an exercise would have a "secret lab" scenario.

---

# Introduction

You are tasked to collate the research of several top-secret research labs.

The facilities submitted their findings to you in separate files. To anticipate future updates, you cannot copy their code. It is important to access the formulas directly from the files and integrate them into your project.

---

# Files

```cpp
# happiness_lab.h

int friendship_index(int hug_factor, int cozy_variance);
int food_hyper_factor(int restaurants_per_capita, int cost_factor, int variety);
int workforce_overload_trigger(int work_force_index; int social_security);

```

```cpp
# entertainment_division.h

int doom_scrolling_malus(int news_engangement_parameter, int click_rate);
int good_news_spread(int acceptance_quota, int cat_invariance, int y2k_hype);

```

```cpp
# caulsality_department.h

int hapy_citizen_primer (int good_news_spread, int workforce_overload_trigger);
int media_contact_rate (int workforce_overload_trigger, int doom_scrolling_malus, int bjarne_uncertainty);

```

# Instructions

Your task is to combine the existing formulas into the "better world" index.

The other secret labs provide you with the research to fill in the missing parts of your work.

Your field studies suggest the following criteria, to finish your project.

```text
The better world index is defined by the friendship multiplied by hyper good food.
Additional citizen happiness has to be added, divided by the overload of the workforce.
Finally everything has to be multiplied by the media
```

**Comment by gelbelle** [comment]
I think you're very wise to have a concept just about header files. I started C for March and was totally lost and confused until I watched Erik's intro video. I've never touched C++ and only did a handful of exercises on the C track so I think I qualify as the no experience expert. :)

I presume you're going to add more to the instructions you have there so far, but here are a couple of things I noticed. Does the ```food_hyper_factor``` function return something that indicates "good"? I'm unclear what "additional citizen happiness" refers to. It looks like you have to add that int to your friendship * hyper good food total and then divide by ```workforce_overload_trigger```

Did I read that right? If you've got files anywhere I would be happy to be your guinea pig.

**Comment by vaeng** [comment]
Concept has to be split into smaller parts.
