### ISSUE TITLE
[Fix] Number's introduction misses addition assignment

### ISSUE THREAD

**Issue by vaeng** [exercism/cpp#619]
Number's introduction misses addition assignment and other similar operators like `-=` and `*=`.

**Comment by vaeng** [comment]
Also, increment and decrement are missing.

**Comment by tesarect** [comment]
This would be my 1st contribution, ever. Can i take this up?
if so, you mean to add [all operators](https://cplusplus.com/doc/tutorial/operators/) under separate headings ?

**Comment by vaeng** [comment]
@tesarect 
Hello and thank you for taking the time to contribute.
I think it would really stretch the whole thing if each operator had its own heading.

Also I added increments and decrements in the loop concept. So it is mainly left to explain all the +=, *=, %= etc variation. I think one heading to explain the principle is enough.

You have to edit the instruction file and the about file to be complete.

**Comment by tesarect** [comment]
@vaeng , I have raised a PR and im sorry, please forgive me if i had made mistakes in the PR and do correct me.

**Comment by vaeng** [comment]
> @vaeng , I have raised a PR and im sorry, please forgive me if i had made mistakes in the PR and do correct me.

No need to be sorry, I am happy that you are taking the effort to contribute. Thanks. I will look at the PR.

**Comment by tesarect** [comment]
[Update numbers introduction - Fixed #636](https://github.com/exercism/cpp/pull/636)

**Comment by tesarect** [comment]
#636

**Comment by tesarect** [comment]
@vaeng thanks a lot for the opportunity
