### ISSUE TITLE
Update relevant documents after numbers change

### ISSUE THREAD

**Issue by vaeng** [exercism/cpp#638]
About.md was not updated with introduction.md for numbers concept. Same for the exercise introduction of the relevant exercises that use the numbers' introduction.md file to generate theirs.

**Comment by tesarect** [comment]
@vaeng , Im sorry that i missed out to notice this while updating the introduction.md file. Can i take this up.
And can you help in getting clear understanding with exactly what content has to be updated in About.md w.r.t introduction.md and the relevant exercises.

**Comment by vaeng** [comment]
Sure, you can do this.

There is only one concept exercise that uses the numbers template. So it is basically two files that need copy-pasting:

- concepts/numbers/about.md
- exercises/concept/freelancer-rates/.docs/introduction.md

**Comment by providentapartment** [comment]
Remember that accuracy and attention to detail are essential when updating documents after numerical data changes. Keeping records up-to-date is crucial for making informed decisions and maintaining data integrity.
