### ISSUE TITLE
[Fix] Classes : about.md is empty.

### ISSUE THREAD

**Issue by vaeng** [exercism/cpp#650]
Again. I'll never learn it.

**Comment by vaeng** [comment]
introduction.md needs to be copied.

**Comment by BethanyG** [comment]
on it.  😉   ... but perhaps we should template it, so that at minimum it copies `introduction.md`??

**Comment by vaeng** [comment]
I always leave it out, so the main discussion is not spread over two almost identical files.
Then I promise to add it after the introduction.md is done.

**Comment by BethanyG** [comment]
🤔   I wonder if adding a comment to the empty file when its created would help?  Something like:

_**Note:** Once the `introduction.md` is complete, copy it here._

**Comment by vaeng** [comment]
I would like to have a template for the about.md file, like the one in configlet that builds the introduction for exercises
