### ISSUE TITLE
Add Function in C++ Concepts

### ISSUE THREAD

**Issue by leap-heng** [exercism/cpp#660]
Hello there, I have not yet seen the function in C++ concepts been added to the repository yet. However these are my initial points to be added.

- Function description
- Function declaration
- Function definition
- Function call
- void Functions
- Function overloading
- Function template
- and Default arguments

Thank you and more suggestions are welcome :)

**Comment by vaeng** [comment]
I think some of the concepts are coveredin the [basics concept](https://exercism.org/tracks/cpp/concepts/basics).
`void` was inserted in the [reference concept](https://exercism.org/tracks/cpp/concepts/references).

I would like to keep this to overloading and default arguments and use them for something like an extended lasagna exercise.

Templates are more advanced, and I think we should what with the introduction and not do too much in one concept.
What do you think, @leap-heng?
