### ISSUE TITLE
last-will: `weak` attributes cause problems with Clang

### ISSUE THREAD

**Issue by siebenschlaefer** [exercism/cpp#670]
When compiling a (correct) solution of the last-will exercise with Clang (version 15.0.7 on Linux) I get the following error:
```
/vagrant/exercism/cpp/last-will/last_will_test.cpp:30:53: error: attribute declaration must precede definition [-Werror,-Wignored-attributes]
    int assemble_account_number(int) __attribute__((weak));
                                                    ^
/vagrant/exercism/cpp/last-will/last_will.cpp:45:9: note: previous definition is here
    int assemble_account_number(int secret_modifier) {
        ^
/vagrant/exercism/cpp/last-will/last_will_test.cpp:31:40: error: attribute declaration must precede definition [-Werror,-Wignored-attributes]
    int assemble_code() __attribute__((weak));
                                       ^
/vagrant/exercism/cpp/last-will/last_will.cpp:50:9: note: previous definition is here
    int assemble_code() {
        ^
```

For some reason Clang doesn't like this `__attribute__((weak))`.  
I couldn't find a quick solution so I'm opening this issue.

**Comment by siebenschlaefer** [comment]
What seem to work is moving the these `weak` declarations (lines [28-35](https://github.com/exercism/cpp/blob/ae6b85aef4135821b064ffce53828fe189291891/exercises/concept/last-will/last_will_test.cpp#L28-L35)) to the beginning of the file, *before* `#include "last_will.cpp"
I've tested that with GCC-9.5.0, GCC-12.1.0, Clang-11.1.0, and Clang-15.0.7 on Linux.

**Comment by vaeng** [comment]
Thanks for finding this! Now we only need the same thing to prep a class to make the test run when it is not implemented. Do you have an idea?
