### ISSUE TITLE
making-the-grades: explain static_cast

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/cpp#678]
I don't see any mention in the instructions on how to actually use `static_cast`. We don't necessarily need an example, but maybe mention that `static_cast` is a function (or at least can be called as a function)?

**Comment by vaeng** [comment]
`static_cast` can be found earlier in the tree under the [numbers concept](https://exercism.org/tracks/cpp/concepts/numbers).  Maybe a short refresher is better?

**Comment by ErikSchierboom** [comment]
Ah, I missed that. [My solution there](https://exercism.org/tracks/cpp/exercises/freelancer-rates/solutions/ErikSchierboom) doesn't use `static_cast`, which might be why it didn't stick.
