### ISSUE TITLE
Reverse string task requires 2 files for tests to pass

### ISSUE THREAD

**Issue by anton-ptashnik** [exercism/cpp#687]
I solved the task in `reverse_string.cpp` and rebuilding with `make` produced output below:

```
/home/bman/Documents/dev/exercism/cpp/exercises/practice/reverse-string/reverse_string_test.cpp:10:35: error: ‘reverse_string’ is not a member of ‘reverse_string’; did you mean ‘reverse_string’?
   10 |     REQUIRE("" == reverse_string::reverse_string(""));
      |                                   ^~~~~~~~~~~~~~
/home/bman/Documents/dev/exercism/cpp/exercises/practice/reverse-string/reverse_string.h:4:11: note: ‘reverse_string’ declared here
    4 | namespace reverse_string {
      |           ^~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/reverse-string.dir/build.make:76: CMakeFiles/reverse-string.dir/reverse_string_test.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:85: CMakeFiles/reverse-string.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

It appeared there is a header file `reverse_string.h` where I need to add a signature definition too. Tests passed locally then but failed on Exercism after publishing `reverse_string.cpp` with my solution. It appeared I need to publish both reverse_string.cpp and reverse_string.h for the solution to be accepted.
It seems to be an extra complication and a user should be required to publish a cpp file only as it is done for other tasks like:
- Log levels https://github.com/exercism/cpp/tree/main/exercises/concept/log-levels
- Lasagna https://github.com/exercism/cpp/tree/main/exercises/concept/lasagna
- Last will https://github.com/exercism/cpp/tree/main/exercises/concept/last-will

**Comment by siebenschlaefer** [comment]
Hello Anton,

We prefer to have these discussions on the [Forum](https://forum.exercism.org/c/programming/cpp/78), that's what this issue has been closed automatically. 

As for this specific issue: The syllabus and its concept exercises are a relatively new addition to the C++ track, and one of the major difficulties was to structure them in a way each concept and concept exercise only deals with one or two aspects of the language. Therefore @vaeng decided to omit `.h` files (and I agree with that decision).  
But in practice C++ programmers use `.h` files all the time, and all *practice exercises* on the C++ track here on Exercism do that, too. So it's the *concept exercises* that deviate, and I strongly believe that we should keep `.h` files in the practice exercises.

If you still think that we should remove `.h` files from some/all practice exercises, or if you want to contribute anything else, please post your ideas on the forum and try to reach a consensus.

Cheers!
