### ISSUE TITLE
queen-attack: compile error without useful information

### ISSUE THREAD

**Issue by nozomirin** [exercism/cpp#722]
Here is my solution: 
queen_attack.h
```cpp
#if !defined(QUEEN_ATTACK_H)
#define QUEEN_ATTACK_H
#include <utility>
namespace queen_attack {
    class chess_board {
    public:
        chess_board(std::pair<int, int> white, std::pair<int, int> black);
        std::pair<int, int> white() const;
        std::pair<int, int> black() const;
        bool can_attack() const;
    private:
        bool is_valid(std::pair<int, int> chess) const;
        bool at_diagonal() const;
        std::pair<int, int> white_;
        std::pair<int, int> black_;
    };
}  // namespace queen_attack

#endif // QUEEN_ATTACK_H
```
queen_attack.cpp
```cpp
#include "queen_attack.h"
#include <stdexcept>
#include <cmath>
namespace queen_attack {
chess_board::chess_board(std::pair<int, int> white, std::pair<int, int> black): white_(white), black_(black) {
    if (!is_valid(white) || !is_valid(black) || white == black) {
        //throw std::domain_error("The range should be in [1-8]");
    }
}

std::pair<int, int> chess_board::white() const {
    return white_;
}
std::pair<int, int> chess_board::black() const {
    return black_;
}

bool chess_board::can_attack() const {
    return white_.first == black_.first || white_.second == black_.second || at_diagonal();
}

bool chess_board::is_valid(std::pair<int, int> chess) const{
    if (chess.first <= 8 && chess.first > 0 && chess.second <= 8 && chess.second > 0) {
        return true;
    }
    return false;
}
bool chess_board::at_diagonal() const {
    return std::abs(white_.first - black_.first) == std::abs(white_.second - black_.second);
}
}  // namespace queen_attack

```
If I just commented the line that throws the domain_error exception, it compiles but can't pass the test.
But if I throw the exception there, I got this:
We received the following error when we ran your code:
make[2]: *** [CMakeFiles/test_queen-attack.dir/build.make:70: CMakeFiles/test_queen-attack] Error 3
make[1]: *** [CMakeFiles/Makefile2:111: CMakeFiles/test_queen-attack.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

And somehow, the Test page get wired...
![test](https://github.com/exercism/cpp/assets/35720515/54588979-e5d7-4b6a-8814-1b82fbc35d47)

**Comment by siebenschlaefer** [comment]
This error report has three aspects: 

- First, and maybe the most important one four you (@nozomirin) this solution considers coordinates valid that are in the range [1, 8]. You might want to double-check the tests, they use a slightly different range.
- When a solution throws an error where the tests do not expect one that results in an empty error message. I know that is sub-optimal but we haven't yet come to an agreement how that should be handle, on a conceptual and a technical level.
- The "weird" test page looks like a bug. @nozomirin, would you be so kind to tell us about your browser, it's version, your operating system, and if possible how to reproduce this issue??

**Comment by nozomirin** [comment]
@siebenschlaefer Thanks for your help! 
I changed the range and it works.
For the weird page, I can't reproduce it. I just modified the code and ran tests. I relaunched the browser before, the problem just gone.
If these information can help you,

the browser: chrome Version 116.0.5845.110 (Official Build) (64-bit)
os: gentoo
core: 6.1.46

**Comment by nozomirin** [comment]
@siebenschlaefer It seems that the weird test page problem happens every time I open a new exercise. After I clicked back to exercise and continue in editor, it disappeared.

**Comment by nozomirin** [comment]
eh... I just opened two and it appeared twice but the third one doesn't appear. I don't know whether some build errors in the last exercise triggered it. Sorry.
