### ISSUE TITLE
pop-count: The header file tab is missing.

### ISSUE THREAD

**Issue by nozomirin** [exercism/cpp#740]
This exercise has passed before, but today I found it doesn't compile.
It seems that the header file, which I modified before, has not been saved.
And now the tab is also missing.
![2023-11-03_10-48](https://github.com/exercism/cpp/assets/35720515/66a90c39-6d11-493e-adea-c1d7318b6029)

**Comment by vaeng** [comment]
Hello @nozomirin,

thank you for raising the issue. I can't see how this is connected to the cpp track. The .meta data looks fine (https://github.com/exercism/cpp/blob/main/exercises/practice/pop-count/.meta/config.json)  Would you be so kind and raise the issue on the forums?

**Comment by nozomirin** [comment]
OK @vaeng
