### ISSUE TITLE
ESP-AT: CMake error: Does not match the generator used previously: Ninja

### ISSUE THREAD

**Issue by shlomo-edu** [exercism/cpp#752]
I downloaded the ESP-AT project from Github and compiled it in Visual Studio Code.
I had several errors in the CMakeFiles.txt which I resolved with help of ChatGPT (I fixed the "string" commands).
But,
After all issues were resolved, it generated the following in the OUPUT tab:
`AT-Commands/esp-at -Bc:/esp-idf/esp-idf/examples/AT-Commands/esp-at/build -G "MinGW Makefiles"
[cmake] Not searching for unused variables given on the command line.
[cmake] CMake Error: Error: generator : MinGW Makefiles
[cmake] Does not match the generator used previously: Ninja
[cmake] Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.
`
I don't know how to continue.

**Comment by vaeng** [comment]
What is the ` ESP-AT` project? Are you sure you are in the correct repository @shlomo-edu ?

**Comment by shlomo-edu** [comment]
Actually I made a mistake of trying to compile the project.
I then realized that I can use the provided binaries, which I work with now.
It works OK for me so I will close this issue.
