### ISSUE TITLE
log-levels concept exercise needs a more fleshed-out stub

### ISSUE THREAD

**Issue by glennj** [exercism/cpp#799]
Two points
* this is an exercise about strings, so the student should not have to worry about the mechanics of functions
* working in the web editor, the student can't see the tests so they don't know what they should be called.

https://discord.com/channels/854117591135027261/1157359032760287302/1205523943021219850

**Comment by glennj** [comment]
The stub file could contain this:
```cpp
namespace log_line {
    std::string message(const std::string& line) {
        // return the message
    }

    std::string log_level(const std::string& line) {
        // return the log level
    }

    std::string reformat(const std::string& line) {
        // return the reformatted message
    }
}
```

**Comment by vaeng** [comment]
I agree with you, the students can learn probably learn more from strings, when the functions are out of the way. At this point they do not know about `const` and references yet, so I would keep it very basic.

**Comment by vaeng** [comment]
I made a pr #806
