### ISSUE TITLE
@ahans as maintainer?

### ISSUE THREAD

**Issue by iHiD** [exercism/cpp#900]
@ahans 👋  

You've also passed the threshold to become a maintainer of this track :) Would you be happy to be appointed? 

Thanks!

**Comment by vaeng** [comment]
That would be a nice addition :)

**Comment by ahans** [comment]
@ErikSchierboom Similarly to the C track I can try to help out here as well! :100:

**Comment by ErikSchierboom** [comment]
Awesome. Thank you!

You should receive an invite to join the org and the team now. You'll also get access to the #maintainers channel on Discord if your Exercism and Discord accounts [are linked](https://exercism.org/settings/integrations).

You can learn more about being a maintainer [here](https://exercism.org/docs/community/maintainers)

Thanks so much for your work, and welcome to the team :)
