### ISSUE TITLE
Exercises are not compiled with "warnings as errors" with MSVC (Microsoft Visual C++).

### ISSUE THREAD

**Issue by heijp06** [exercism/cpp#922]
When compiling with CLang or GCC warnings are treated as errors. The [relevant part of CMakeLists.txt](https://github.com/exercism/cpp/blob/3d106a5b8768c17c716fd0692013ffe4ae9937de/exercises/practice/hello-world/CMakeLists.txt#L48) is this:

```cmake
if("${CMAKE_CXX_COMPILER_ID}" MATCHES "(GNU|Clang)")
    set_target_properties(${exercise} PROPERTIES
        COMPILE_FLAGS "-Wall -Wextra -Wpedantic -Werror"
    )
endif()
```

For MSVC no such option is set. As a consequence code that contains mistakes that the user should be guarded against (e.g. not returning a value in all code paths) compiles without errors. Also when uploading the code to the website the stricter rules on the server will make code that compiled locally fail there.

Setting warnings as errors for MSVC is not that hard. There is an [MSVC specific part in CMakeLists.txt](https://github.com/exercism/cpp/blob/3d106a5b8768c17c716fd0692013ffe4ae9937de/exercises/practice/hello-world/CMakeLists.txt#L57):

```cmake
# Tell MSVC not to warn us about unchecked iterators in debug builds
if(${MSVC})
    set_target_properties(${exercise} PROPERTIES
        COMPILE_DEFINITIONS_DEBUG _SCL_SECURE_NO_WARNINGS)
endif()
```

This can be changed to:

```cmake
# Tell MSVC not to warn us about unchecked iterators in debug builds
if(${MSVC})
    set_target_properties(${exercise} PROPERTIES
        COMPILE_DEFINITIONS_DEBUG _SCL_SECURE_NO_WARNINGS
        COMPILE_FLAGS "/WX")
endif()
```

Compiling with `/WX` will make MSVC treat warnings as errors.

If this change is deemed useful, I can pick it up.

---

As an aside, the GCC/CLang `COMPILE_FLAGS`: `-Wall -Wextra -Wpedantic` also raise the warning level of the compiler.

This is also possible for MSVC. The default warning level for MSVC is `/W3`, this can be set to `/W4` or `/Wall`. I experimented with those levels and I do NOT propose setting those higher levels. E.g. with `/WX /W4` the following code: 

```cpp
char capital_a = std::toupper('a');
```

Will fail to compile because the compiler warns (as error) about a possible loss of precision when setting `capital_a` (a `char`) to the return value of `toupper()` (an `int`).

**Comment by heijp06** [comment]
@vaeng I opened this issue, but it was auto-closed.

I am not really sure how to navigate this. I do not want to spam the forum, so this seemed more appropriate. Maybe I should also stop spamming here :slightly_smiling_face:, let me know what you think.

I can pick up the issue if you think it is worthwhile. The change I propose to make is one that I consistently make to `CMakeList.txt` when solving exercises on Windows.

**Comment by vaeng** [comment]
No need to post to the forums, if you ping me here. The forums are pretty quiet for CPP, so I don't mind the post there either. Do what feels best for you 

In general I really appreciate the work you do for Windows, as it is often overlooked by our regulars, but heavily used by beginners. 

Please keep in mind that I'm currently pretty busy and the other maintainers are somewhat inactive at the moment.
