### ISSUE TITLE
Document formatting conventions for this repo

### ISSUE THREAD

**Issue by LegalizeAdulthood** [exercism/cpp#93]
Formatting styles vary widely in the C++ community.  Document the formatting style used by this repo.
- Namespaces don't indent
- Whitespace as per editor config #92 
- Identifier conventions
- Separate test cases with single blank line
- Separate test case phases (setup, exercise, verify, teardown) with a single blank line
- Test only one behavior per test case

Others?

**Comment by exklamationmark** [comment]
What do you think about using the [Google's C++ style guide](https://github.com/google/styleguide)?
While it's not necessarily the golden rules, it's comprehensive enough & contain good practices.

Plus, there is [a linter](https://github.com/google/styleguide/tree/gh-pages/cpplint) that can be used to check the code.

**Comment by patricksjackson** [comment]
I opened #274 to enforce this with a checker which will cover most of this. It won't cover everything, but it will get us most of the way there.

I'm going to close this in favor of the other one to be clear about what we need.
