### ISSUE TITLE
crypto-square wrong tests

### ISSUE THREAD

**Issue by celavek** [exercism/cpp#97]
Hi,

I think that the last 2 tests for the crypto-square problem are wrong. You can verify that by 
stacking the segment in output of the normalized cipher text which should yield the plaintext in 
normalized form:

E.g.

```
vrela 
epems     ==>     veeorptieeprlmapasoo (far away from truth) 
etpao 
oirpo

```

Correct

```
vrel 
aepe 
mset       ==>  vampiresarepeopletoo
paoo 
irpo

```

Also the following result

`msemoa anindn inndla etltsh ui
`
does not satisfy the property stated in the README 

> Imperfect squares will have n empty spaces. Those spaces should be distributed evenly across the last n rows.

**Comment by patricksjackson** [comment]
Yea, you're correct on that. It appears everybody in this track just followed the tests and didn't pay much attention to the readme.

Would you like to fix it?

**Comment by LegalizeAdulthood** [comment]
I shamelessly imitated the JavaScript track while implementing the C++ track 😺

**Comment by celavek** [comment]
@patricksjackson OK, I could give it a try. I'm not sure about the time frame as I came across it while implementing the D track and my main focus is right now on that.

**Comment by kytrinyx** [comment]
There's a ginormous discussion about this over in the metadata repo: https://github.com/exercism/x-common/issues/190

We have a canonical data set here, I think: https://github.com/exercism/x-common/blob/master/crypto-square.json

**Comment by patricksjackson** [comment]
Oops, this is still an issue. I'm looking into it.

The correct test suite is now located here: https://github.com/exercism/problem-specifications/blob/master/exercises/crypto-square/canonical-data.json
